-- sql provisional pendent de revisar entre el grup pero veure si cambiem alguna cosa
DROP DATABASE IF EXISTS nutri;
CREATE DATABASE IF NOT EXISTS nutri CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nutri;

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    correo VARCHAR(100) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100),
    altura DECIMAL(5,2),
    peso DECIMAL(5,2),
    fecha_nacimiento DATE,
    genero ENUM('masculino', 'femenino', 'otro') DEFAULT 'otro',
    objetivo VARCHAR(255),
    alergias VARCHAR(255),
    enfermedades VARCHAR(255),
    preferencias_comida VARCHAR(255),
    actividad_fisica ENUM('sedentario', 'ligero', 'moderado', 'intenso', 'muy intenso') DEFAULT 'moderado',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dieta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    numero_comidas_dia INT CHECK (numero_comidas_dia >= 3 AND numero_comidas_dia <= 5),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_dieta FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE comida_modelo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo_comida ENUM('desayuno', 'almuerzo', 'comida', 'merienda', 'cena') NOT NULL,
    calorias_totales INT NOT NULL,
    apta_diabetes BOOLEAN DEFAULT TRUE,
    apta_hipertension BOOLEAN DEFAULT TRUE,
    apta_hipercolesterolemia BOOLEAN DEFAULT TRUE,
    apta_celiacos BOOLEAN DEFAULT TRUE,
    apta_renal BOOLEAN DEFAULT TRUE,
    apta_anemia BOOLEAN DEFAULT TRUE,
    apta_obesidad BOOLEAN DEFAULT TRUE,
    apta_hipotiroidismo BOOLEAN DEFAULT TRUE,
    apta_colon_irritable BOOLEAN DEFAULT TRUE,
    sin_lactosa BOOLEAN DEFAULT FALSE,
    sin_frutos_secos BOOLEAN DEFAULT FALSE,
    sin_marisco BOOLEAN DEFAULT FALSE,
    sin_pescado_azul BOOLEAN DEFAULT FALSE,
    sin_huevo BOOLEAN DEFAULT FALSE,
    sin_soja BOOLEAN DEFAULT FALSE,
    sin_legumbres BOOLEAN DEFAULT FALSE,
    sin_sesamo BOOLEAN DEFAULT FALSE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ingrediente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(300),
    calorias INT NOT NULL,
    proteinas DECIMAL(5,2),
    grasas DECIMAL(5,2),
    carbohidratos DECIMAL(5,2),
    fibra DECIMAL(5,2),
    azucar DECIMAL(5,2),
    tipo ENUM('fruta', 'verdura', 'carne', 'pescado', 'cereal', 'lácteo', 'legumbre', 'fruto_seco', 'semilla', 'bebida', 'otro') DEFAULT 'otro',
    creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE comida_ingrediente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comida_modelo_id INT NOT NULL,
    ingrediente_id INT NOT NULL,
    cantidad DECIMAL(6,2) NOT NULL, 
    unidad ENUM('g', 'ml', 'unidad') DEFAULT 'g',
    CONSTRAINT fk_comida_modelo FOREIGN KEY (comida_modelo_id) REFERENCES comida_modelo(id) ON DELETE CASCADE,
    CONSTRAINT fk_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingrediente(id) ON DELETE CASCADE
);

CREATE TABLE comida_diaria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dieta_id INT NOT NULL,
    dia_semana ENUM('lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo') NOT NULL,
    tipo_comida ENUM('desayuno', 'almuerzo', 'comida', 'merienda', 'cena') NOT NULL,
    comida_modelo_id INT NOT NULL,
    FOREIGN KEY (dieta_id) REFERENCES dieta(id) ON DELETE CASCADE,
    FOREIGN KEY (comida_modelo_id) REFERENCES comida_modelo(id) ON DELETE CASCADE
);
CREATE TABLE receta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(500),
    instrucciones TEXT NOT NULL,
    tiempo_preparacion INT NOT NULL,
    dificultad ENUM('fácil', 'media', 'difícil') DEFAULT 'media',
    raciones INT NOT NULL DEFAULT 1,
    imagen_url VARCHAR(255),
    visible BOOLEAN DEFAULT TRUE,
    creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE receta_ingrediente (
    receta_id INT,
    ingrediente_id INT,
    cantidad DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (receta_id, ingrediente_id),
    FOREIGN KEY (receta_id) REFERENCES receta(id) ON DELETE CASCADE,
    FOREIGN KEY (ingrediente_id) REFERENCES ingrediente(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE seguimiento_dieta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dieta_id INT NOT NULL,
    receta_id INT NOT NULL,
    dia_semana ENUM('lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo') NOT NULL,
    comida ENUM('desayuno', 'almuerzo', 'comida', 'merienda', 'cena') NOT NULL,
    hora TIME,
    porciones DECIMAL(4,2) DEFAULT 1.0,
    consumido BOOLEAN DEFAULT FALSE,
    notas TEXT,
    fecha DATE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dieta_id) REFERENCES dieta(id) ON DELETE CASCADE,
    FOREIGN KEY (receta_id) REFERENCES receta(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tema_foro (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    contenido TEXT NOT NULL,
    categoria ENUM('dieta', 'recetas', 'entrenamiento', 'general') DEFAULT 'general',
    num_respuestas INT DEFAULT 0,
    visitas INT DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_foro FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE like_foro (
    usuario_id INT NOT NULL,
    tema_foro_id INT NOT NULL,
    PRIMARY KEY (usuario_id, tema_foro_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (tema_foro_id) REFERENCES tema_foro(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE respuesta_foro (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tema_foro_id INT NOT NULL,
    usuario_id INT NOT NULL,
    contenido TEXT NOT NULL,
    visitas INT DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_respuesta_tema FOREIGN KEY (tema_foro_id) REFERENCES tema_foro(id) ON DELETE CASCADE,
    CONSTRAINT fk_respuesta_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE like_respuesta_foro (
    usuario_id INT NOT NULL,
    respuesta_id INT NOT NULL,
    PRIMARY KEY (usuario_id, respuesta_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (respuesta_id) REFERENCES respuesta_foro(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE articulo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    resumen VARCHAR(300),
    contenido TEXT NOT NULL,
    imagen_url VARCHAR(255),
    categoria ENUM('nutricion', 'salud', 'recetas', 'deporte', 'otro') DEFAULT 'nutricion',
    autor VARCHAR(100),
    fecha_publicacion DATE,
    visible BOOLEAN DEFAULT TRUE,
    visitas INT DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE like_articulo (
    usuario_id INT NOT NULL,
    articulo_id INT NOT NULL,
    PRIMARY KEY (usuario_id, articulo_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (articulo_id) REFERENCES articulo(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE comentario_articulo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    articulo_id INT NOT NULL,
    usuario_id INT NOT NULL,
    contenido TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (articulo_id) REFERENCES articulo(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE favorito_articulo (
    usuario_id INT NOT NULL,
    articulo_id INT NOT NULL,
    PRIMARY KEY (usuario_id, articulo_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (articulo_id) REFERENCES articulo(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glosario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    termino VARCHAR(100) NOT NULL UNIQUE,
    definicion TEXT NOT NULL,
    fuente VARCHAR(255),
    categoria ENUM('concepto','macronutriente','micronutriente','vitamina','mineral','suplemento','dieta','deporte','otro') DEFAULT 'otro',
    imagen_url VARCHAR(255),
    visible BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE multimedia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    url VARCHAR(255) NOT NULL,
    tipo ENUM('video', 'infografia', 'pdf', 'web', 'otro') DEFAULT 'video',
    categoria ENUM('nutricion', 'salud', 'ejercicio', 'mentalidad', 'otro') DEFAULT 'nutricion',
    visible BOOLEAN DEFAULT TRUE,
    fecha_publicacion DATE,
    creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ingrediente (nombre, descripcion, calorias, proteinas, grasas, carbohidratos, fibra, azucar, tipo) VALUES
('Espinaca', 'Verdura de hoja verde rica en hierro y fibra.', 23, 2.9, 0.4, 1.1, 2.2, 0.4, 'verdura'),
('Acelga', 'Hortaliza de hoja ancha, muy baja en calorías.', 20, 1.8, 0.2, 1.8, 1.6, 0.4, 'verdura'),
('Zanahoria', 'Raíz comestible rica en betacarotenos.', 41, 0.9, 0.2, 9.6, 2.8, 4.7, 'verdura'),
('Calabacín', 'Verdura versátil y ligera, rica en agua.', 17, 1.2, 0.3, 3.1, 1.0, 1.7, 'verdura'),
('Berenjena', 'Verdura de piel morada y textura esponjosa.', 25, 1.0, 0.2, 6.0, 3.0, 3.5, 'verdura'),
('Pimiento rojo', 'Hortaliza dulce y rica en vitamina C.', 31, 1.0, 0.3, 6.0, 2.1, 4.2, 'verdura'),
('Tomate', 'Fruto usado como verdura, rico en licopeno.', 18, 0.9, 0.2, 3.9, 1.2, 2.6, 'verdura'),
('Brócoli', 'Verdura crucífera rica en antioxidantes.', 34, 2.8, 0.4, 6.6, 2.6, 1.7, 'verdura'),
('Coliflor', 'Flor comestible, rica en vitamina C.', 25, 2.0, 0.3, 5.0, 2.0, 1.9, 'verdura'),
('Cebolla', 'Bulbo aromático usado como base de cocción.', 40, 1.1, 0.1, 9.3, 1.7, 4.2, 'verdura'),
('Lechuga romana', 'Hortaliza de hoja verde ideal para ensaladas.', 15, 1.4, 0.2, 2.9, 1.3, 0.8, 'verdura'),
('Lechuga iceberg', 'Lechuga crujiente con alto contenido en agua.', 14, 0.9, 0.1, 3.0, 1.2, 1.4, 'verdura'),
('Apio', 'Verdura de tallo larga y fibrosa, muy diurética.', 16, 0.7, 0.2, 3.5, 1.6, 1.8, 'verdura'),
('Puerro', 'Verdura de sabor suave, parecida a la cebolla.', 29, 1.5, 0.3, 7.6, 1.8, 3.9, 'verdura'),
('Nabo', 'Raíz blanca rica en agua y muy baja en calorías.', 28, 0.9, 0.1, 6.4, 1.8, 3.8, 'verdura'),
('Rábano', 'Raíz pequeña y picante común en ensaladas.', 16, 0.7, 0.1, 3.4, 1.6, 1.9, 'verdura'),
('Remolacha', 'Raíz roja rica en antioxidantes y azúcares.', 43, 1.6, 0.2, 9.6, 2.8, 6.8, 'verdura'),
('Col lombarda', 'Variedad de col morada, rica en antocianinas.', 31, 1.4, 0.2, 7.4, 2.1, 3.8, 'verdura'),
('Col rizada (kale)', 'Verdura de hoja verde muy nutritiva.', 49, 4.3, 0.9, 8.8, 3.6, 2.3, 'verdura'),
('Repollo', 'Verdura de hoja verde de sabor suave.', 25, 1.3, 0.1, 5.8, 2.5, 3.2, 'verdura'),
('Hinojo', 'Verdura aromática con sabor a anís.', 31, 1.2, 0.2, 7.3, 3.1, 3.9, 'verdura'),
('Endibia', 'Verdura de sabor ligeramente amargo.', 17, 0.9, 0.1, 3.4, 1.6, 0.8, 'verdura'),
('Alcachofa', 'Flor comestible muy rica en fibra y antioxidantes.', 47, 3.3, 0.2, 10.5, 5.4, 0.5, 'verdura'),
('Judía verde', 'Vaina comestible rica en fibra y vitaminas.', 31, 1.8, 0.2, 7.1, 3.1, 1.4, 'verdura'),
('Pepino', 'Verdura muy refrescante y baja en calorías.', 12, 0.6, 0.1, 2.2, 0.5, 1.4, 'verdura'),
('Escarola', 'Verdura de hoja rizada y sabor amargo, ideal para ensaladas.', 17, 1.3, 0.2, 2.0, 3.1, 0.8, 'verdura'),
('Borraja', 'Verdura tradicional aragonesa, con tallos comestibles.', 21, 1.8, 0.3, 3.1, 1.5, 1.0, 'verdura'),
('Cardo', 'Verdura de invierno similar a la alcachofa, rica en fibra.', 17, 0.9, 0.1, 3.0, 1.5, 0.8, 'verdura'),
('Grelos', 'Brotes tiernos de nabo muy usados en Galicia.', 22, 2.2, 0.3, 1.9, 2.6, 0.6, 'verdura'),
('Berza', 'Col rizada de textura gruesa, típica de cocidos.', 32, 2.5, 0.3, 5.4, 3.5, 1.4, 'verdura'),
('Coles de Bruselas', 'Pequeñas coles con sabor intenso.', 43, 3.4, 0.3, 8.9, 3.8, 2.2, 'verdura'),
('Champiñón', 'Hongo comestible muy bajo en calorías.', 22, 3.1, 0.3, 3.3, 1.0, 1.0, 'verdura'),
('Seta ostra', 'Hongo comestible de textura carnosa.', 33, 3.3, 0.4, 6.1, 2.3, 1.0, 'verdura'),
('Raíz de apio (apionabo)', 'Raíz gruesa y aromática del apio.', 42, 1.5, 0.3, 9.2, 1.8, 1.6, 'verdura'),
('Habas verdes', 'Legumbre tierna usada como verdura.', 55, 4.0, 0.5, 9.0, 4.0, 1.5, 'verdura'),
('Manzana', 'Fruta crujiente y refrescante, rica en fibra.', 52, 0.3, 0.2, 13.8, 2.4, 10.4, 'fruta'),
('Plátano', 'Fruta tropical rica en potasio y energía rápida.', 89, 1.1, 0.3, 22.8, 2.6, 12.2, 'fruta'),
('Naranja', 'Fruta cítrica rica en vitamina C.', 47, 0.9, 0.1, 11.8, 2.4, 9.3, 'fruta'),
('Pera', 'Fruta jugosa con alto contenido de agua y fibra.', 57, 0.4, 0.1, 15.2, 3.1, 9.8, 'fruta'),
('Melocotón', 'Fruta dulce de verano, rica en antioxidantes.', 39, 0.9, 0.3, 9.5, 1.5, 8.4, 'fruta'),
('Albaricoque', 'Fruta pequeña con alto contenido en betacaroteno.', 48, 1.4, 0.4, 11.1, 2.0, 9.2, 'fruta'),
('Uva', 'Fruta dulce en racimos, rica en azúcares naturales.', 69, 0.7, 0.2, 18.1, 0.9, 15.5, 'fruta'),
('Fresa', 'Fruta roja y aromática, baja en calorías.', 32, 0.7, 0.3, 7.7, 2.0, 4.9, 'fruta'),
('Kiwi', 'Fruta ácida y verde, muy rica en vitamina C.', 61, 1.1, 0.5, 14.7, 3.0, 9.0, 'fruta'),
('Cereza', 'Fruta pequeña y dulce, rica en antioxidantes.', 50, 1.0, 0.3, 12.2, 1.6, 8.0, 'fruta'),
('Piña', 'Fruta tropical jugosa, rica en vitamina C y bromelina.', 50, 0.5, 0.1, 13.1, 1.4, 9.9, 'fruta'),
('Mango', 'Fruta carnosa, dulce y rica en betacarotenos.', 60, 0.8, 0.4, 15.0, 1.6, 13.7, 'fruta'),
('Papaya', 'Fruta tropical suave con enzimas digestivas como la papaína.', 43, 0.5, 0.3, 10.8, 1.7, 7.8, 'fruta'),
('Maracuyá', 'Fruta exótica con semillas comestibles y alto contenido en fibra.', 97, 2.2, 0.4, 23.4, 10.4, 11.2, 'fruta'),
('Guayaba', 'Fruta tropical muy rica en vitamina C y antioxidantes.', 68, 2.6, 1.0, 14.3, 5.4, 8.9, 'fruta'),
('Chirimoya', 'Fruta tropical dulce, de pulpa blanca y cremosa.', 75, 1.6, 0.7, 18.0, 3.0, 14.7, 'fruta'),
('Lichi', 'Fruta pequeña, dulce y aromática, con alto contenido en vitamina C.', 66, 0.8, 0.4, 16.5, 1.3, 15.2, 'fruta'),
('Pitahaya (fruta del dragón)', 'Fruta exótica con alto contenido de agua y fibra.', 50, 1.1, 0.4, 11.0, 3.0, 8.0, 'fruta'),
('Tamarindo', 'Fruta tropical agridulce rica en fibra y minerales.', 239, 2.8, 0.6, 62.5, 5.1, 38.8, 'fruta'),
('Carambola (fruta estrella)', 'Fruta exótica en forma de estrella, refrescante y baja en calorías.', 31, 1.0, 0.3, 6.7, 2.8, 3.7, 'fruta'),
('Frambuesa', 'Fruta roja pequeña, ácida y rica en fibra y antioxidantes.', 52, 1.2, 0.7, 11.9, 6.5, 4.4, 'fruta'),
('Arándano', 'Fruta pequeña azulada, muy rica en antocianinas.', 57, 0.7, 0.3, 14.5, 2.4, 9.7, 'fruta'),
('Mora', 'Fruta oscura y jugosa, con alto contenido en vitamina C.', 43, 1.4, 0.5, 9.6, 5.3, 4.9, 'fruta'),
('Grosella roja', 'Fruta ácida y brillante, usada en mermeladas y zumos.', 56, 1.4, 0.2, 13.8, 4.3, 7.4, 'fruta'),
('Grosella negra', 'Fruta rica en vitamina C y antocianinas.', 63, 1.4, 0.4, 15.4, 5.0, 7.4, 'fruta'),
('Endrina', 'Fruta silvestre de sabor muy ácido, base del pacharán.', 54, 0.9, 0.5, 13.5, 2.5, 9.5, 'fruta'),
('Escaramujo', 'Fruto del rosal silvestre, muy rico en vitamina C.', 162, 1.6, 0.3, 38.2, 24.1, 2.6, 'fruta'),
('Dátil seco', 'Fruta muy energética, rica en azúcares naturales y potasio.', 282, 2.5, 0.4, 75.0, 8.0, 63.4, 'fruta'),
('Higo seco', 'Fruta deshidratada con alto contenido en fibra y calcio.', 249, 3.3, 0.9, 63.9, 9.8, 47.9, 'fruta'),
('Uva pasa', 'Uva deshidratada, dulce y rica en antioxidantes.', 299, 3.1, 0.5, 79.2, 3.7, 59.2, 'fruta'),
('Ciruela pasa', 'Ciruela desecada rica en fibra soluble y potasio.', 240, 2.2, 0.4, 63.9, 7.1, 38.1, 'fruta'),
('Albaricoque seco', 'Fruta deshidratada de sabor intenso, rica en hierro y fibra.', 241, 3.4, 0.5, 62.6, 7.3, 53.4, 'fruta'),
('Granada', 'Fruta de otoño rica en antioxidantes y vitamina C.', 83, 1.7, 1.2, 18.7, 4.0, 13.7, 'fruta'),
('Caqui', 'Fruta dulce de otoño, muy energética y rica en vitamina A.', 70, 0.6, 0.2, 18.6, 3.6, 15.0, 'fruta'),
('Melón', 'Fruta refrescante de verano, con alto contenido en agua.', 34, 0.8, 0.2, 8.2, 0.9, 7.8, 'fruta'),
('Sandía', 'Fruta de verano muy hidratante, ideal para días calurosos.', 30, 0.6, 0.2, 7.6, 0.4, 6.2, 'fruta'),
('Higo fresco', 'Fruta de verano-otoño, dulce y muy digestiva.', 74, 0.8, 0.3, 19.2, 2.9, 16.3, 'fruta'),
('Níspero', 'Fruta de primavera con sabor entre ácido y dulce.', 47, 0.4, 0.2, 12.1, 1.7, 6.5, 'fruta'),
('Mandarina', 'Cítrico de invierno fácil de pelar y rico en vitamina C.', 53, 0.8, 0.3, 13.3, 1.8, 10.5, 'fruta'),
('Castaña', 'Fruto de otoño-invierno, alto en hidratos y muy saciante.', 196, 2.0, 1.3, 45.5, 8.1, 10.6, 'fruta'),
('Leche entera', 'Líquido nutritivo proveniente de la vaca, fuente de calcio.', 61, 3.2, 3.6, 4.8, 0.0, 4.8, 'lácteo'),
('Leche semidesnatada', 'Leche con menos grasa que la entera pero mantiene el calcio.', 47, 3.2, 1.6, 4.9, 0.0, 4.9, 'lácteo'),
('Leche desnatada', 'Leche sin grasa, ideal para dietas hipocalóricas.', 35, 3.4, 0.1, 5.0, 0.0, 5.0, 'lácteo'),
('Yogur natural', 'Producto fermentado a partir de la leche, fuente de probióticos.', 61, 3.5, 3.3, 4.7, 0.0, 4.7, 'lácteo'),
('Yogur griego 0%', 'Yogur espeso sin grasa, alto en proteínas.', 59, 10.0, 0.4, 3.6, 0.0, 3.6, 'lácteo'),
('Queso fresco', 'Queso blanco, tierno y suave, bajo en grasa.', 98, 11.0, 4.0, 3.0, 0.0, 2.8, 'lácteo'),
('Queso curado', 'Queso madurado de sabor intenso y alto valor calórico.', 402, 25.0, 33.0, 1.3, 0.0, 0.5, 'lácteo'),
('Queso de cabra', 'Queso elaborado con leche de cabra, de sabor fuerte.', 364, 22.0, 30.0, 2.0, 0.0, 0.5, 'lácteo'),
('Kéfir', 'Bebida fermentada con probióticos naturales.', 52, 3.6, 3.0, 4.0, 0.0, 3.8, 'lácteo'),
('Mantequilla', 'Grasa láctea sólida obtenida de la nata.', 717, 0.9, 81.1, 0.1, 0.0, 0.1, 'lácteo'),
('Queso crema', 'Queso untable suave, ideal para tostadas o repostería.', 342, 6.2, 34.0, 3.3, 0.0, 2.5, 'lácteo'),
('Leche condensada', 'Leche concentrada y azucarada, muy energética.', 321, 7.9, 8.7, 54.4, 0.0, 54.0, 'lácteo'),
('Nata para cocinar', 'Grasa láctea líquida, usada en salsas y cremas.', 195, 2.1, 20.0, 3.0, 0.0, 2.9, 'lácteo'),
('Nata para montar', 'Nata con más grasa, ideal para repostería.', 345, 2.1, 36.0, 2.8, 0.0, 2.8, 'lácteo'),
('Leche sin lactosa', 'Leche tratada para eliminar la lactosa, fácil de digerir.', 45, 3.2, 1.5, 4.9, 0.0, 2.0, 'lácteo'),
('Yogur sin lactosa', 'Yogur fermentado apto para intolerantes a la lactosa.', 50, 4.0, 2.0, 4.8, 0.0, 4.5, 'lácteo'),
('Queso rallado', 'Mezcla de quesos curados rallados para fundir.', 371, 25.0, 30.0, 1.3, 0.0, 0.9, 'lácteo'),
('Requesón', 'Producto lácteo suave, con alto contenido en agua.', 98, 11.0, 4.3, 3.0, 0.0, 2.8, 'lácteo'),
('Leche evaporada', 'Leche concentrada sin azúcar, para cocinar o café.', 135, 6.8, 7.5, 10.0, 0.0, 10.0, 'lácteo'),
('Batido de chocolate', 'Bebida láctea azucarada con sabor a cacao.', 72, 3.2, 1.2, 12.0, 0.0, 11.5, 'lácteo'),
('Lenteja cocida', 'Legumbre pequeña rica en hierro y proteínas vegetales.', 116, 9.0, 0.4, 20.1, 7.9, 1.8, 'legumbre'),
('Garbanzos cocidos', 'Legumbre redonda y cremosa, base del hummus.', 164, 8.9, 2.6, 27.4, 7.6, 4.8, 'legumbre'),
('Judía blanca cocida', 'Legumbre blanca suave, usada en cocidos y potajes.', 127, 8.7, 0.5, 23.7, 6.4, 0.6, 'legumbre'),
('Judía roja cocida', 'Legumbre rojiza rica en antioxidantes y fibra.', 127, 8.4, 0.5, 22.8, 6.4, 0.3, 'legumbre'),
('Soja cocida', 'Legumbre amarilla muy rica en proteína vegetal.', 172, 16.6, 9.0, 9.9, 6.0, 3.0, 'legumbre'),
('Alubia pinta cocida', 'Variedad de judía moteada, muy nutritiva.', 135, 9.0, 0.5, 24.0, 6.7, 0.5, 'legumbre'),
('Habas secas cocidas', 'Legumbre grande y algo astringente, rica en hierro.', 110, 8.0, 0.5, 19.0, 5.4, 1.0, 'legumbre'),
('Guistante cocido', 'Legumbre verde dulce, rica en proteínas y fibra.', 84, 5.4, 0.4, 14.5, 5.1, 5.0, 'legumbre'),
('Lenteja roja cocida', 'Lenteja sin piel de cocción rápida, muy digestiva.', 120, 9.0, 0.4, 20.0, 5.0, 1.5, 'legumbre'),
('Edamame', 'Soja verde inmadura, snack muy proteico.', 121, 11.9, 5.2, 8.9, 5.2, 2.2, 'legumbre'),
('Lenteja beluga cocida', 'Lenteja pequeña y negra, con textura firme y sabor suave.', 116, 9.2, 0.4, 20.1, 8.0, 1.7, 'legumbre'),
('Lenteja verde cocida', 'Lenteja de tamaño mediano y color verdoso, muy usada en ensaladas.', 117, 9.0, 0.4, 20.2, 7.5, 1.6, 'legumbre'),
('Azuki cocido', 'Judía roja japonesa, usada en platos dulces y salados.', 128, 7.5, 0.1, 25.0, 7.3, 0.3, 'legumbre'),
('Judión cocido', 'Legumbre grande y blanca típica de La Granja.', 130, 8.5, 0.5, 22.0, 6.5, 0.4, 'legumbre'),
('Soja texturizada', 'Proteína vegetal obtenida de la soja, usada como sustituto de carne.', 326, 49.0, 1.0, 18.0, 13.0, 7.0, 'legumbre'),
('Lupino cocido', 'Legumbre amarilla con alto contenido proteico, consumida encurtida.', 119, 15.6, 2.9, 12.4, 3.7, 1.1, 'legumbre'),
('Mungo cocido', 'Judía verde pequeña, muy usada en cocina asiática.', 105, 7.0, 0.4, 19.0, 7.0, 1.5, 'legumbre'),
('Guisante seco cocido', 'Guisante partido, más proteico que el fresco.', 118, 8.3, 0.4, 21.1, 6.5, 2.0, 'legumbre'),
('Soja negra cocida', 'Variedad oscura de soja, rica en antioxidantes.', 170, 15.5, 9.0, 10.0, 6.0, 2.0, 'legumbre'),
('Cacahuete cocido', 'Técnicamente una legumbre, muy calórico y proteico.', 318, 25.8, 24.4, 7.2, 8.0, 2.0, 'legumbre'),
('Merluza', 'Pescado blanco suave, bajo en grasa y muy digerible.', 72, 12.0, 2.0, 0.0, 0.0, 0.0, 'pescado'),
('Salmón', 'Pescado azul graso, fuente de omega-3 y proteínas.', 208, 20.4, 13.0, 0.0, 0.0, 0.0, 'pescado'),
('Atún', 'Pescado azul de carne roja y muy proteico.', 132, 23.0, 4.0, 0.0, 0.0, 0.0, 'pescado'),
('Bacalao fresco', 'Pescado blanco salado tradicional, bajo en grasa.', 82, 17.8, 0.7, 0.0, 0.0, 0.0, 'pescado'),
('Sardina', 'Pescado azul pequeño y graso, muy rico en calcio.', 208, 25.0, 11.0, 0.0, 0.0, 0.0, 'pescado'),
('Lenguado', 'Pescado blanco plano de sabor fino y textura delicada.', 91, 16.5, 2.0, 0.0, 0.0, 0.0, 'pescado'),
('Caballa', 'Pescado azul con alto contenido en ácidos grasos omega-3.', 205, 19.0, 14.0, 0.0, 0.0, 0.0, 'pescado'),
('Pez espada', 'Pescado grande de carne firme, ideal para la plancha.', 144, 20.5, 6.0, 0.0, 0.0, 0.0, 'pescado'),
('Trucha', 'Pescado de río semigraso, fuente de proteína y fósforo.', 119, 20.5, 4.0, 0.0, 0.0, 0.0, 'pescado'),
('Rape', 'Pescado blanco gelatinoso, muy usado en caldos.', 68, 14.5, 0.3, 0.0, 0.0, 0.0, 'pescado'),
('Arroz integral cocido', 'Cereal completo con mayor fibra y nutrientes.', 111, 2.6, 0.9, 23.0, 1.8, 0.4, 'cereal'),
('Avena en copos', 'Cereal integral rico en fibra soluble y energía sostenida.', 389, 13.0, 6.9, 66.3, 10.6, 1.0, 'cereal'),
('Quinoa cocida', 'Pseudocereal rico en proteína y aminoácidos esenciales.', 120, 4.1, 1.9, 21.3, 2.8, 0.9, 'cereal'),
('Pan blanco', 'Producto de harina refinada, bajo en fibra.', 265, 8.0, 3.2, 49.0, 2.5, 5.0, 'cereal'),
('Pan integral', 'Pan elaborado con harina de trigo integral, más saciante.', 247, 8.8, 3.5, 41.0, 6.0, 4.0, 'cereal'),
('Maíz cocido', 'Grano dulce muy consumido como guarnición o en ensaladas.', 96, 3.4, 1.5, 18.7, 2.7, 6.3, 'cereal'),
('Cuscús cocido', 'Sémola de trigo muy usada en platos del norte de África.', 112, 3.8, 0.2, 23.2, 1.4, 0.1, 'cereal'),
('Bulgur cocido', 'Trigo precocido con textura similar al arroz.', 83, 3.1, 0.2, 18.6, 4.5, 0.1, 'cereal'),
('Pasta cocida', 'Alimento hecho de harina de trigo y agua, muy versátil.', 131, 5.0, 1.1, 25.0, 1.8, 0.7, 'cereal'),
('Trigo sarraceno cocido', 'Pseudocereal sin gluten, muy nutritivo y fácil de digerir.', 92, 3.4, 0.6, 19.9, 2.7, 0.3, 'cereal'),
('Amaranto cocido', 'Pseudocereal sin gluten, con alto contenido proteico.', 102, 3.8, 1.6, 19.0, 2.1, 1.7, 'cereal'),
('Mijo cocido', 'Cereal sin gluten de grano pequeño, usado en dietas ligeras.', 119, 3.5, 1.0, 23.7, 1.3, 0.1, 'cereal'),
('Espelta cocida', 'Cereal ancestral con más proteína que el trigo común.', 127, 5.5, 1.0, 24.0, 3.8, 0.5, 'cereal'),
('Harina de trigo', 'Producto base para pan, pasta y repostería.', 364, 10.3, 1.0, 76.2, 2.7, 0.3, 'cereal'),
('Corn flakes', 'Copos de maíz tostados, cereal de desayuno clásico.', 357, 7.5, 0.4, 84.0, 3.0, 7.0, 'cereal'),
('Arroz inflado', 'Arroz tostado e inflado, muy usado en cereales y snacks.', 375, 6.9, 0.7, 87.5, 1.2, 0.3, 'cereal'),
('Copos de trigo integral', 'Cereal de desayuno alto en fibra y sin azúcar añadido.', 340, 11.2, 2.4, 72.0, 11.0, 1.0, 'cereal'),
('Harina de avena', 'Versión molida del grano, muy usada en repostería saludable.', 379, 13.3, 6.7, 67.7, 10.1, 1.1, 'cereal'),
('Fideos de arroz cocidos', 'Pasta sin gluten elaborada con arroz, muy común en cocina asiática.', 108, 2.0, 0.2, 25.0, 0.5, 0.1, 'cereal'),
('Arroz blanco', 'Cereal básico sin gluten, muy digestivo.', 365, 7.1, 0.7, 80.0, 1.3, 0.1, 'cereal'),
('Arroz integral', 'Versión completa del arroz, con más fibra y micronutrientes.', 362, 7.5, 2.7, 76.2, 3.4, 0.8, 'cereal'),
('Maíz', 'Cereal sin gluten, muy versátil y base de muchos productos.', 365, 9.4, 4.7, 74.3, 7.3, 1.1, 'cereal'),
('Copos de maíz', 'Cereal de desayuno sin gluten (versión certificada).', 370, 7.5, 1.0, 83.0, 2.5, 6.5, 'cereal'),
('Quinoa', 'Pseudocereal sin gluten, muy completo nutricionalmente.', 368, 14.1, 6.1, 64.2, 7.0, 1.0, 'cereal'),
('Trigo sarraceno', 'Pseudocereal sin gluten, ideal para panes y crepes.', 343, 13.3, 3.4, 71.5, 10.0, 0.9, 'cereal'),
('Mijo', 'Cereal ancestral sin gluten, usado en papillas o guarniciones.', 378, 11.0, 4.2, 73.0, 8.5, 1.5, 'cereal'),
('Fideos de arroz', 'Pasta sin gluten a base de arroz, muy usada en cocina asiática.', 364, 7.0, 0.9, 80.0, 1.2, 0.3, 'cereal'),
('Harina de arroz', 'Harina sin gluten usada para panes, tortitas y repostería.', 366, 6.0, 1.5, 80.1, 2.4, 0.5, 'cereal'),
('Pan sin gluten', 'Pan elaborado con harinas sin gluten como arroz o maíz.', 249, 5.8, 3.2, 49.0, 5.0, 4.0, 'cereal'),
('Almendra cruda', 'Fruto seco muy nutritivo, rico en calcio y vitamina E.', 579, 21.2, 49.9, 21.6, 12.5, 4.4, 'fruto_seco'),
('Nuez', 'Fruto seco con alto contenido en ácidos grasos omega-3.', 654, 15.2, 65.2, 13.7, 6.7, 2.6, 'fruto_seco'),
('Avellana', 'Fruto seco redondo, muy energético y sabroso.', 628, 14.1, 60.8, 16.7, 9.7, 4.0, 'fruto_seco'),
('Anacardo', 'Fruto seco cremoso y algo dulce, ideal como snack.', 553, 18.2, 43.8, 30.2, 3.3, 5.9, 'fruto_seco'),
('Pistacho', 'Fruto seco verde con gran contenido en proteínas y fibra.', 562, 20.2, 45.4, 27.5, 10.3, 7.7, 'fruto_seco'),
('Macadamia', 'Fruto seco muy graso, de textura crujiente y suave.', 718, 7.9, 75.8, 13.8, 8.6, 4.6, 'fruto_seco'),
('Piñón', 'Semilla comestible del pino, muy valorada en cocina.', 673, 13.7, 68.4, 13.1, 3.7, 3.6, 'fruto_seco'),
('Castaña seca', 'Fruto seco de otoño, con menos grasa y más hidratos.', 369, 6.0, 3.0, 79.0, 8.0, 14.0, 'fruto_seco'),
('Nuez pecana', 'Variedad americana de nuez, más dulce y aceitosa.', 691, 9.2, 72.0, 14.0, 9.6, 4.0, 'fruto_seco'),
('Almendra tostada', 'Versión ligeramente tostada, mantiene la mayoría de nutrientes.', 598, 20.6, 52.0, 21.0, 11.8, 4.2, 'fruto_seco');

INSERT INTO ingrediente (nombre, descripcion, calorias, proteinas, grasas, carbohidratos, fibra, azucar, tipo) VALUES
('Agua mineral', 'Bebida esencial sin calorías ni nutrientes energéticos.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'bebida'),
('Zumo de naranja natural', 'Bebida exprimida rica en vitamina C y azúcares naturales.', 45, 0.7, 0.2, 10.0, 0.2, 8.4, 'bebida'),
('Zumo de piña envasado', 'Bebida dulce a base de concentrado de piña.', 55, 0.4, 0.1, 13.0, 0.1, 12.0, 'bebida'),
('Refresco de cola', 'Bebida carbonatada con cafeína y alto contenido en azúcar.', 42, 0.0, 0.0, 10.6, 0.0, 10.6, 'bebida'),
('Refresco de cola zero', 'Versión sin azúcar del refresco clásico.', 1, 0.0, 0.0, 0.1, 0.0, 0.0, 'bebida'),
('Cerveza sin alcohol', 'Bebida fermentada con bajo contenido en alcohol.', 22, 0.3, 0.0, 5.0, 0.0, 1.7, 'bebida'),
('Bebida vegetal de almendra', 'Alternativa vegetal a la leche, baja en calorías.', 17, 0.6, 1.1, 0.3, 0.2, 0.2, 'bebida'),
('Bebida vegetal de soja', 'Alternativa vegetal rica en proteína vegetal.', 33, 3.3, 1.8, 0.6, 0.4, 0.4, 'bebida'),
('Té verde infusionado', 'Bebida antioxidante sin calorías si se toma sin azúcar.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'bebida'),
('Café solo', 'Infusión estimulante sin calorías si se toma sin azúcar.', 2, 0.3, 0.0, 0.0, 0.0, 0.0, 'bebida'),
('Bebida de soja', 'Alternativa vegetal rica en proteínas, similar nutricionalmente a la leche.', 33, 3.3, 1.8, 0.6, 0.4, 0.4, 'bebida'),
('Bebida de almendra sin azúcar', 'Bebida vegetal ligera y baja en calorías.', 13, 0.5, 1.1, 0.1, 0.3, 0.1, 'bebida'),
('Bebida de avena', 'Bebida vegetal cremosa, fuente de betaglucanos.', 47, 1.0, 1.5, 7.0, 0.8, 4.0, 'bebida'),
('Bebida de arroz', 'Bebida vegetal muy digestiva, rica en hidratos.', 49, 0.1, 1.0, 10.0, 0.2, 5.5, 'bebida'),
('Bebida de coco', 'Bebida vegetal refrescante, con grasas saludables.', 20, 0.2, 1.2, 2.2, 0.1, 1.9, 'bebida'),
('Bebida de avellanas', 'Bebida vegetal con sabor dulce y aromático.', 59, 1.2, 2.6, 8.8, 0.4, 5.8, 'bebida'),
('Bebida de espelta', 'Bebida de cereal con sabor suave, algo más proteica.', 50, 1.4, 1.0, 8.6, 0.8, 3.8, 'bebida'),
('Bebida de quinoa', 'Bebida vegetal exótica con aminoácidos esenciales.', 39, 1.2, 1.3, 6.0, 0.6, 3.5, 'bebida'),
('Bebida de chufa (horchata sin azúcar)', 'Bebida vegetal típica de Valencia, refrescante y digestiva.', 40, 0.6, 2.4, 4.8, 0.5, 2.0, 'bebida'),
('Bebida de mijo', 'Bebida vegetal menos común, sin gluten y fácil de digerir.', 36, 0.8, 1.1, 6.5, 0.6, 3.0, 'bebida'),
('Bebida isotónica con azúcar', 'Bebida deportiva con sales minerales y azúcares de absorción rápida.', 26, 0.0, 0.0, 6.4, 0.0, 6.0, 'bebida'),
('Bebida isotónica sin azúcar', 'Versión sin azúcares, aporta electrolitos sin calorías.', 4, 0.0, 0.0, 0.9, 0.0, 0.1, 'bebida'),
('Agua con electrolitos', 'Agua mineral enriquecida con sodio, potasio y magnesio.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'bebida'),
('Bebida de recuperación post-entreno', 'Bebida isotónica con carbohidratos y algo de proteína.', 55, 2.0, 0.5, 10.5, 0.0, 8.0, 'bebida'),
('Bebida energética ligera', 'Versión isotónica con cafeína y vitaminas B.', 30, 0.0, 0.0, 7.3, 0.0, 7.0, 'bebida'),
('Refresco de naranja', 'Bebida carbonatada con sabor cítrico y azúcares añadidos.', 39, 0.0, 0.0, 9.7, 0.0, 9.7, 'bebida'),
('Refresco de limón', 'Bebida gasificada con aroma a limón y azúcar.', 38, 0.0, 0.0, 9.5, 0.0, 9.5, 'bebida'),
('Tónica', 'Bebida carbonatada con sabor amargo por la quinina.', 34, 0.0, 0.0, 8.5, 0.0, 8.5, 'bebida'),
('Gaseosa', 'Refresco sin saborizantes, solo agua carbonatada y azúcar.', 27, 0.0, 0.0, 6.6, 0.0, 6.6, 'bebida'),
('Bitter kas', 'Refresco amargo con extractos vegetales, típico en aperitivos.', 33, 0.0, 0.0, 8.1, 0.0, 8.1, 'bebida'),
('Refresco de manzana', 'Bebida carbonatada con aroma y sabor a manzana.', 40, 0.0, 0.0, 10.0, 0.0, 9.8, 'bebida'),
('Refresco de té con limón', 'Infusión fría azucarada y gasificada.', 28, 0.0, 0.0, 7.0, 0.0, 6.8, 'bebida'),
('Ternera magra', 'Corte limpio de ternera, alto en proteína y bajo en grasa.', 133, 21.3, 4.7, 0.0, 0.0, 0.0, 'carne'),
('Ternera picada', 'Carne de ternera molida, usada en guisos y hamburguesas.', 215, 18.0, 15.0, 0.0, 0.0, 0.0, 'carne'),
('Cerdo magro', 'Corte de cerdo bajo en grasa, como el lomo.', 143, 21.0, 5.5, 0.0, 0.0, 0.0, 'carne'),
('Lomo de cerdo', 'Corte limpio y magro, típico en filetes o asados.', 165, 20.0, 9.0, 0.0, 0.0, 0.0, 'carne'),
('Costilla de cerdo', 'Corte graso y sabroso, muy usado en barbacoas.', 286, 17.5, 25.0, 0.0, 0.0, 0.0, 'carne'),
('Cordero pierna', 'Carne roja sabrosa y jugosa, típica de celebraciones.', 206, 20.0, 14.0, 0.0, 0.0, 0.0, 'carne'),
('Chuleta de cerdo', 'Corte mixto con hueso, muy consumido a la plancha.', 250, 18.5, 20.0, 0.0, 0.0, 0.0, 'carne'),
('Chorizo curado', 'Embutido típico con pimentón, alto en grasa y sabor.', 455, 24.0, 38.0, 1.0, 0.0, 1.0, 'carne'),
('Jamón serrano', 'Pierna curada de cerdo, muy rica en proteína.', 241, 30.5, 14.0, 0.5, 0.0, 0.5, 'carne'),
('Morcilla', 'Embutido de sangre, arroz y grasa, muy calórico.', 379, 15.0, 35.0, 3.0, 0.0, 0.5, 'carne'),
('Jamón cocido (York)', 'Carne cocida magra, baja en grasa y salada.', 126, 18.0, 5.0, 1.0, 0.0, 1.0, 'carne'),
('Pechuga de pavo cocida', 'Fiambre magro, alto en proteína y bajo en grasa.', 102, 20.0, 2.0, 1.0, 0.0, 0.5, 'carne'),
('Salchichón curado', 'Embutido graso de cerdo con especias.', 420, 25.0, 36.0, 1.0, 0.0, 1.0, 'carne'),
('Fuet', 'Embutido catalán fino y curado, de cerdo.', 455, 24.0, 39.0, 1.5, 0.0, 1.5, 'carne'),
('Lomo embuchado', 'Corte de lomo curado con especias, bajo en carbohidratos.', 250, 37.0, 12.0, 0.5, 0.0, 0.5, 'carne'),
('Sobrasada', 'Embutido untuoso típico de Baleares, con pimentón.', 449, 14.0, 43.0, 1.0, 0.0, 0.5, 'carne'),
('Longaniza', 'Embutido curado de cerdo, similar al chorizo pero más suave.', 410, 23.0, 35.0, 1.5, 0.0, 1.0, 'carne'),
('Salami', 'Embutido curado y especiado, popular en bocadillos.', 430, 22.0, 38.0, 1.0, 0.0, 1.0, 'carne'),
('Mortadela', 'Fiambre de cerdo de textura blanda y sabor suave.', 311, 13.0, 28.0, 1.0, 0.0, 1.0, 'carne'),
('Salchicha tipo Frankfurt', 'Embutido cocido ahumado, típico de perritos calientes.', 301, 11.0, 27.0, 2.0, 0.0, 1.5, 'carne'),
('Hamburguesa de ternera', 'Carne picada de ternera en forma de hamburguesa, lista para cocinar.', 230, 18.0, 17.0, 0.5, 0.0, 0.2, 'carne'),
('Hamburguesa de cerdo', 'Versión más grasa que la de ternera, sabor intenso.', 260, 17.0, 21.0, 0.5, 0.0, 0.3, 'carne'),
('Hamburguesa mixta', 'Mezcla de carne de ternera y cerdo, habitual en supermercados.', 245, 17.5, 19.0, 0.6, 0.0, 0.3, 'carne'),
('Hamburguesa vegetal (no vegana)', 'Preparado vegetal con huevo y leche, sabor cárnico.', 160, 12.0, 6.0, 12.0, 3.0, 2.0, 'carne'),
('Albóndigas de carne', 'Bolas de carne picada cocinadas con salsa o guarnición.', 240, 15.0, 18.0, 2.5, 0.5, 1.0, 'carne'),
('Carne picada mixta', 'Carne molida de ternera y cerdo, sin formar.', 220, 18.0, 16.0, 0.0, 0.0, 0.0, 'carne'),
('Filete empanado de cerdo', 'Carne rebozada y frita, muy calórica.', 290, 16.0, 18.0, 15.0, 1.0, 1.0, 'carne'),
('Escalope de ternera', 'Filete rebozado de ternera, crujiente y jugoso.', 265, 17.0, 15.0, 14.0, 1.1, 0.9, 'carne'),
('Brocheta de carne adobada', 'Pincho con trozos de carne sazonada lista para asar.', 190, 20.0, 10.0, 1.0, 0.3, 0.5, 'carne'),
('Carne mechada', 'Carne cocida y desmenuzada, típica en bocadillos.', 225, 22.0, 15.0, 1.0, 0.0, 0.3, 'carne'),
('Semillas de chía', 'Ricas en omega-3, fibra y proteínas vegetales.', 486, 16.5, 30.7, 42.1, 34.4, 0.0, 'semilla'),
('Semillas de lino', 'Fuente vegetal de omega-3 y lignanos, muy digestivas si se muelen.', 534, 18.3, 42.2, 28.9, 27.3, 1.6, 'semilla'),
('Semillas de sésamo', 'Muy calóricas, fuente de calcio, fósforo y proteínas.', 573, 17.7, 49.7, 23.5, 11.8, 0.3, 'semilla'),
('Semillas de calabaza', 'Ricas en zinc, hierro y grasas saludables.', 559, 30.2, 49.0, 10.7, 6.0, 1.4, 'semilla'),
('Semillas de girasol', 'Fuente de vitamina E y grasas monoinsaturadas.', 584, 20.8, 51.5, 20.0, 8.6, 2.6, 'semilla'),
('Semillas de amapola', 'Pequeñas semillas aromáticas, fuente de calcio y fibra.', 525, 18.0, 42.0, 28.1, 20.0, 3.0, 'semilla'),
('Semillas de cáñamo', 'Contienen todos los aminoácidos esenciales, muy completas.', 553, 31.6, 48.8, 8.7, 4.0, 1.5, 'semilla'),
('Semillas de mostaza', 'Pequeñas y picantes, se usan para condimentar.', 508, 26.1, 36.2, 28.1, 12.2, 6.2, 'semilla'),
('Semillas de albahaca', 'Similares a la chía, se hinchan al contacto con agua.', 442, 14.8, 24.4, 43.0, 37.0, 0.0, 'semilla'),
('Semillas de hinojo', 'Aromáticas, se usan como infusión o en cocina.', 345, 15.8, 14.9, 52.3, 39.8, 0.5, 'semilla'),
('Azúcar blanco', 'Edulcorante refinado, aporta solo energía.', 387, 0.0, 0.0, 100.0, 0.0, 100.0, 'otro'),
('Azúcar moreno', 'Azúcar sin refinar, con trazas de melaza.', 380, 0.1, 0.0, 98.0, 0.2, 95.0, 'otro'),
('Miel', 'Edulcorante natural producido por abejas.', 304, 0.3, 0.0, 82.4, 0.2, 82.1, 'otro'),
('Sirope de agave', 'Jarabe vegetal dulce, con bajo índice glucémico.', 310, 0.1, 0.0, 76.0, 0.1, 75.0, 'otro'),
('Stevia', 'Edulcorante natural sin calorías, extraído de plantas.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'otro'),
('Aceite de oliva virgen extra', 'Grasa saludable rica en antioxidantes.', 884, 0.0, 100.0, 0.0, 0.0, 0.0, 'otro'),
('Aceite de girasol', 'Aceite vegetal neutro, rico en vitamina E.', 884, 0.0, 100.0, 0.0, 0.0, 0.0, 'otro'),
('Vinagre de vino', 'Líquido ácido usado como aderezo y conservante.', 21, 0.0, 0.0, 0.0, 0.0, 0.0, 'otro'),
('Sal', 'Condimento básico, no aporta calorías pero sí sodio.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'otro'),
('Pimienta negra', 'Especia picante, usada en múltiples recetas.', 251, 10.4, 3.3, 64.8, 25.3, 0.6, 'otro'),
('Cúrcuma', 'Especia amarilla con propiedades antiinflamatorias.', 354, 7.8, 9.9, 64.9, 21.1, 3.2, 'otro'),
('Canela en polvo', 'Especia dulce muy usada en repostería.', 247, 4.0, 1.2, 81.0, 53.1, 2.2, 'otro'),
('Pimentón dulce', 'Condimento en polvo típico de la cocina española.', 282, 14.1, 13.1, 54.7, 34.9, 10.3, 'otro'),
('Curry', 'Mezcla de especias aromáticas típicas de la India.', 325, 14.3, 14.0, 58.2, 33.0, 2.5, 'otro'),
('Comino', 'Semilla aromática muy usada en cocina árabe y española.', 375, 17.8, 22.3, 44.2, 10.5, 2.3, 'otro'),
('Mostaza en grano', 'Semilla picante y aromática usada en encurtidos y salsas.', 508, 26.1, 36.2, 28.1, 12.2, 6.2, 'otro'),
('Levadura de panadería seca', 'Agente leudante natural, usado en pan y masas.', 325, 40.0, 7.0, 41.0, 26.0, 0.0, 'otro'),
('Levadura química (impulsor)', 'Gasificante usado en bizcochos y repostería.', 97, 0.0, 0.0, 24.3, 0.0, 0.0, 'otro'),
('Masa madre deshidratada', 'Fermento natural en polvo, da sabor y textura al pan.', 255, 11.0, 1.5, 52.0, 3.0, 1.2, 'otro'),
('Bicarbonato sódico', 'Agente alcalino usado como gasificante o antiácido.', 0, 0.0, 0.0, 0.0, 0.0, 0.0, 'otro');

INSERT INTO glosario (termino, definicion, fuente, categoria, imagen_url, visible)
VALUES
('Nutriente', 'Sustancia presente en los alimentos que es necesaria para el crecimiento, desarrollo y mantenimiento de la vida.', 'FAO/OMS', 'concepto', 'https://ejemplo.com/nutriente.jpg', TRUE),
('Caloría', 'Unidad de energía que indica la cantidad de energía que aporta un alimento al cuerpo humano.', 'Organización Mundial de la Salud', 'concepto', 'https://ejemplo.com/caloria.jpg', TRUE),
('Metabolismo', 'Conjunto de procesos químicos que ocurren en el organismo para mantener la vida, incluyendo la conversión de alimentos en energía.', 'MedlinePlus', 'concepto', 'https://ejemplo.com/metabolismo.jpg', TRUE),
('Índice glucémico', 'Medida de la velocidad con la que un alimento eleva el nivel de glucosa en sangre.', 'Harvard Medical School', 'concepto', 'https://ejemplo.com/indice-glucemico.jpg', TRUE),
('Densidad nutricional', 'Cantidad de nutrientes que contiene un alimento en relación con su aporte calórico.', 'EFSA', 'concepto', 'https://ejemplo.com/densidad-nutricional.jpg', TRUE),
('Digestión', 'Proceso por el cual el cuerpo descompone los alimentos en nutrientes que puede absorber y utilizar.', 'NIH', 'concepto', 'https://ejemplo.com/digestion.jpg', TRUE),
('Balance energético', 'Relación entre la energía que se consume a través de los alimentos y la que se gasta en las funciones corporales y actividad física.', 'FAO', 'concepto', 'https://ejemplo.com/balance-energetico.jpg', TRUE),
('Necesidades energéticas', 'Cantidad de energía que una persona requiere diariamente para mantener sus funciones vitales y nivel de actividad.', 'EFSA', 'concepto', 'https://ejemplo.com/necesidades-energeticas.jpg', TRUE),
('Ración', 'Cantidad estándar de un alimento utilizada como referencia para evaluar el consumo.', 'Ministerio de Sanidad España', 'concepto', 'https://ejemplo.com/racion.jpg', TRUE),
('Etiqueta nutricional', 'Información obligatoria que aparece en el envase de los alimentos sobre su composición nutricional.', 'AESAN', 'concepto', 'https://ejemplo.com/etiqueta-nutricional.jpg', TRUE),
('Valor nutricional', 'Conjunto de nutrientes y energía que aporta un alimento por una cantidad determinada.', 'AESAN', 'concepto', 'https://ejemplo.com/valor-nutricional.jpg', TRUE),
('Requerimientos diarios', 'Cantidad estimada de cada nutriente que debe consumir una persona diariamente para mantener la salud.', 'EFSA', 'concepto', 'https://ejemplo.com/requerimientos-diarios.jpg', TRUE),
('Saciedad', 'Sensación de plenitud que indica que no se necesita seguir comiendo.', 'FAO', 'concepto', 'https://ejemplo.com/saciedad.jpg', TRUE),
('Estado nutricional', 'Condición física resultante del equilibrio entre el consumo de nutrientes y las necesidades del organismo.', 'OMS', 'concepto', 'https://ejemplo.com/estado-nutricional.jpg', TRUE),
('Absorción', 'Proceso mediante el cual los nutrientes pasan del sistema digestivo a la sangre o linfa.', 'NIH', 'concepto', 'https://ejemplo.com/absorcion.jpg', TRUE),
('Malnutrición', 'Condición que resulta de una alimentación inadecuada o desequilibrada, ya sea por exceso o defecto.', 'OMS', 'concepto', 'https://ejemplo.com/malnutricion.jpg', TRUE),
('Alimento funcional', 'Alimento que, además de nutrir, proporciona beneficios adicionales para la salud.', 'EFSA', 'concepto', 'https://ejemplo.com/alimento-funcional.jpg', TRUE),
('Biodisponibilidad', 'Proporción de un nutriente que es absorbido y utilizado efectivamente por el organismo.', 'FAO', 'concepto', 'https://ejemplo.com/biodisponibilidad.jpg', TRUE),
('Perfil nutricional', 'Descripción de la cantidad de nutrientes y energía contenida en un alimento o dieta.', 'AESAN', 'concepto', 'https://ejemplo.com/perfil-nutricional.jpg', TRUE),
('Educación nutricional', 'Proceso que permite adquirir conocimientos y hábitos para mejorar la alimentación y la salud.', 'Ministerio de Sanidad', 'concepto', 'https://ejemplo.com/educacion-nutricional.jpg', TRUE),
('Hábitos alimentarios', 'Conjunto de comportamientos adquiridos por una persona o grupo respecto a la elección y consumo de alimentos.', 'FAO', 'concepto', 'https://ejemplo.com/habitos-alimentarios.jpg', TRUE),
('Dieta equilibrada', 'Plan de alimentación que proporciona todos los nutrientes necesarios en cantidades adecuadas para mantener la salud.', 'OMS', 'concepto', 'https://ejemplo.com/dieta-equilibrada.jpg', TRUE),
('Composición corporal', 'Distribución de masa muscular, grasa, hueso y otros componentes en el cuerpo.', 'NIH', 'concepto', 'https://ejemplo.com/composicion-corporal.jpg', TRUE),
('Nutrición personalizada', 'Enfoque dietético adaptado a las necesidades individuales según genética, metabolismo y estilo de vida.', 'EFSA', 'concepto', 'https://ejemplo.com/nutricion-personalizada.jpg', TRUE),
('Alimentación intuitiva', 'Estilo de alimentación basado en señales internas como el hambre y la saciedad, sin restricciones externas.', 'Academy of Nutrition and Dietetics', 'concepto', 'https://ejemplo.com/alimentacion-intuitiva.jpg', TRUE),
('Etiqueta de ingredientes', 'Lista que muestra todos los ingredientes presentes en un producto alimenticio, ordenados por cantidad.', 'AESAN', 'concepto', 'https://ejemplo.com/etiqueta-ingredientes.jpg', TRUE),
('Contaminante alimentario', 'Sustancia no deseada presente en alimentos que puede afectar la salud.', 'EFSA', 'concepto', 'https://ejemplo.com/contaminante-alimentario.jpg', TRUE),
('Nutrigenómica', 'Estudio de cómo los alimentos afectan la expresión genética y el metabolismo.', 'Genomics and Nutrition Journal', 'concepto', 'https://ejemplo.com/nutrigenomica.jpg', TRUE),
('Saciedad hormonal', 'Sensación de plenitud regulada por hormonas como la leptina y la grelina.', 'NIH', 'concepto', 'https://ejemplo.com/saciedad-hormonal.jpg', TRUE),
('Hidratación', 'Estado de equilibrio de líquidos en el organismo, esencial para el funcionamiento celular.', 'OMS', 'concepto', 'https://ejemplo.com/hidratacion.jpg', TRUE),
('Proteínas', 'Macronutrientes esenciales formados por aminoácidos que participan en la construcción y reparación de tejidos.', 'FAO/OMS', 'macronutriente', 'https://ejemplo.com/proteinas.jpg', TRUE),
('Carbohidratos', 'Macronutrientes que constituyen la principal fuente de energía del cuerpo, presentes en alimentos como cereales, frutas y legumbres.', 'EFSA', 'macronutriente', 'https://ejemplo.com/carbohidratos.jpg', TRUE),
('Grasas', 'Nutrientes energéticos que también cumplen funciones estructurales y hormonales, incluyendo grasas saturadas, insaturadas y trans.', 'OMS', 'macronutriente', 'https://ejemplo.com/grasas.jpg', TRUE),
('Fibra dietética', 'Tipo de carbohidrato no digerible que favorece el tránsito intestinal y la salud digestiva.', 'MedlinePlus', 'macronutriente', 'https://ejemplo.com/fibra.jpg', TRUE),
('Agua', 'Elemento vital que actúa como medio de transporte, regula la temperatura y permite múltiples funciones biológicas.', 'FAO', 'macronutriente', 'https://ejemplo.com/agua.jpg', TRUE),
('Vitamina A', 'Vitamina liposoluble que contribuye a la visión, el sistema inmunitario y la salud de la piel.', 'EFSA', 'vitamina', 'https://ejemplo.com/vitamina-a.jpg', TRUE),
('Vitamina D', 'Vitamina liposoluble que favorece la absorción del calcio y el fósforo, esencial para la salud ósea.', 'OMS', 'vitamina', 'https://ejemplo.com/vitamina-d.jpg', TRUE),
('Vitamina E', 'Antioxidante liposoluble que protege las células frente al daño oxidativo.', 'FAO', 'vitamina', 'https://ejemplo.com/vitamina-e.jpg', TRUE),
('Vitamina K', 'Vitamina liposoluble que interviene en la coagulación de la sangre y la salud ósea.', 'NIH', 'vitamina', 'https://ejemplo.com/vitamina-k.jpg', TRUE),
('Calcio', 'Mineral esencial para la formación y mantenimiento de huesos y dientes, también participa en la contracción muscular y la coagulación sanguínea.', 'EFSA', 'mineral', 'https://ejemplo.com/calcio.jpg', TRUE),
('Hierro', 'Mineral necesario para la formación de hemoglobina y el transporte de oxígeno en la sangre.', 'OMS', 'mineral', 'https://ejemplo.com/hierro.jpg', TRUE),
('Magnesio', 'Mineral que participa en más de 300 reacciones bioquímicas del cuerpo, incluyendo la función muscular y nerviosa.', 'NIH', 'mineral', 'https://ejemplo.com/magnesio.jpg', TRUE),
('Zinc', 'Mineral implicado en el sistema inmunológico, la cicatrización y la división celular.', 'FAO', 'mineral', 'https://ejemplo.com/zinc.jpg', TRUE),
('Potasio', 'Mineral que ayuda a mantener el equilibrio de líquidos, la función muscular y la actividad eléctrica del corazón.', 'OMS', 'mineral', 'https://ejemplo.com/potasio.jpg', TRUE),
('Fósforo', 'Mineral importante para la formación de huesos y dientes, así como para la producción de energía celular.', 'EFSA', 'mineral', 'https://ejemplo.com/fosforo.jpg', TRUE),
('Sodio', 'Mineral esencial para el equilibrio de líquidos y la función nerviosa, aunque su exceso puede afectar la salud cardiovascular.', 'AESAN', 'mineral', 'https://ejemplo.com/sodio.jpg', TRUE),
('Yodo', 'Mineral necesario para la producción de hormonas tiroideas que regulan el metabolismo.', 'FAO', 'mineral', 'https://ejemplo.com/yodo.jpg', TRUE),
('Selenio', 'Antioxidante que protege las células del daño y apoya la función inmunitaria y tiroidea.', 'NIH', 'mineral', 'https://ejemplo.com/selenio.jpg', TRUE),
('Cobre', 'Mineral que participa en la producción de energía, la formación de tejidos conectivos y el sistema nervioso.', 'OMS', 'mineral', 'https://ejemplo.com/cobre.jpg', TRUE),
('Manganeso', 'Mineral involucrado en el metabolismo de carbohidratos y lípidos, y en la formación de huesos.', 'EFSA', 'mineral', 'https://ejemplo.com/manganeso.jpg', TRUE),
('Flúor', 'Mineral que fortalece el esmalte dental y previene las caries.', 'OMS', 'mineral', 'https://ejemplo.com/fluor.jpg', TRUE),
('Cromo', 'Mineral que contribuye al metabolismo de la glucosa y mejora la acción de la insulina.', 'NIH', 'mineral', 'https://ejemplo.com/cromo.jpg', TRUE),
('Molibdeno', 'Mineral que forma parte de enzimas implicadas en el metabolismo de aminoácidos y purinas.', 'FAO', 'mineral', 'https://ejemplo.com/molibdeno.jpg', TRUE),
('Cloro', 'Mineral esencial para la producción de jugos gástricos y el equilibrio de líquidos en el organismo.', 'EFSA', 'mineral', 'https://ejemplo.com/cloro.jpg', TRUE),
('Níquel', 'Mineral traza que participa en algunas enzimas, aunque sus funciones en humanos no están completamente claras.', 'EFSA', 'mineral', 'https://ejemplo.com/niquel.jpg', TRUE),
('Silicio', 'Mineral que interviene en la síntesis del colágeno y puede contribuir a la salud ósea y cutánea.', 'NIH', 'mineral', 'https://ejemplo.com/silicio.jpg', TRUE),
('Boro', 'Mineral que podría estar relacionado con el metabolismo del calcio, magnesio y fósforo.', 'FAO', 'mineral', 'https://ejemplo.com/boro.jpg', TRUE),
('Litio', 'Oligoelemento que se estudia por su posible papel en la función neurológica y la salud mental.', 'NIH', 'mineral', 'https://ejemplo.com/litio.jpg', TRUE),
('Vanadio', 'Oligoelemento presente en pequeñas cantidades en el cuerpo, se investiga su papel en el metabolismo de lípidos y glucosa.', 'EFSA', 'mineral', 'https://ejemplo.com/vanadio.jpg', TRUE),
('Proteína en polvo', 'Suplemento alimenticio utilizado para aumentar la ingesta proteica, común en dietas deportivas o hipocalóricas.', 'EFSA', 'suplemento', 'https://ejemplo.com/proteina-polvo.jpg', TRUE),
('Creatina', 'Compuesto natural que mejora el rendimiento en ejercicios de alta intensidad y favorece la recuperación muscular.', 'NIH', 'suplemento', 'https://ejemplo.com/creatina.jpg', TRUE),
('Omega-3', 'Ácidos grasos esenciales que se suplementan por su efecto antiinflamatorio y beneficios cardiovasculares.', 'FAO', 'suplemento', 'https://ejemplo.com/omega-3.jpg', TRUE),
('Multivitamínico', 'Suplemento que combina varias vitaminas y minerales para cubrir requerimientos nutricionales diarios.', 'OMS', 'suplemento', 'https://ejemplo.com/multivitaminico.jpg', TRUE),
('Vitamina D3', 'Suplemento liposoluble usado para mantener niveles óptimos de vitamina D, especialmente en personas con baja exposición solar.', 'EFSA', 'suplemento', 'https://ejemplo.com/vitamina-d3.jpg', TRUE),
('Colágeno hidrolizado', 'Suplemento que aporta péptidos de colágeno, favoreciendo la salud articular, cutánea y ósea.', 'NIH', 'suplemento', 'https://ejemplo.com/colageno.jpg', TRUE),
('Magnesio en comprimidos', 'Forma suplementada de magnesio utilizada para prevenir calambres musculares y mejorar la calidad del sueño.', 'FAO', 'suplemento', 'https://ejemplo.com/magnesio-suplemento.jpg', TRUE),
('Cafeína', 'Suplemento estimulante que mejora la concentración, el estado de alerta y el rendimiento deportivo.', 'EFSA', 'suplemento', 'https://ejemplo.com/cafeina.jpg', TRUE),
('BCAA', 'Aminoácidos de cadena ramificada que se suplementan para preservar masa muscular y acelerar la recuperación.', 'NIH', 'suplemento', 'https://ejemplo.com/bcaa.jpg', TRUE),
('Glutamina', 'Aminoácido que puede apoyar la recuperación muscular y la función inmunológica en situaciones de alta exigencia física.', 'FAO', 'suplemento', 'https://ejemplo.com/glutamina.jpg', TRUE),
('Dieta mediterránea', 'Patrón alimentario basado en el consumo de frutas, verduras, legumbres, pescado, aceite de oliva y cereales integrales, característico de los países del Mediterráneo.', 'Fundación Dieta Mediterránea', 'dieta', 'https://ejemplo.com/dieta-mediterranea.jpg', TRUE),
('Dieta cetogénica', 'Dieta alta en grasas, moderada en proteínas y muy baja en carbohidratos, orientada a inducir cetosis para el uso de grasa como fuente principal de energía.', 'EFSA', 'dieta', 'https://ejemplo.com/dieta-cetogenica.jpg', TRUE),
('Dieta vegana', 'Dieta basada exclusivamente en alimentos de origen vegetal, excluyendo cualquier producto de origen animal.', 'The Vegan Society', 'dieta', 'https://ejemplo.com/dieta-vegana.jpg', TRUE),
('Dieta vegetariana', 'Dieta que excluye carne y pescado, pero puede incluir productos animales como huevos o lácteos.', 'Academy of Nutrition and Dietetics', 'dieta', 'https://ejemplo.com/dieta-vegetariana.jpg', TRUE),
('Dieta DASH', 'Dieta diseñada para reducir la presión arterial, rica en frutas, verduras, granos integrales y baja en sodio y grasas saturadas.', 'NIH', 'dieta', 'https://ejemplo.com/dieta-dash.jpg', TRUE),
('Dieta sin gluten', 'Dieta que elimina el gluten, una proteína presente en trigo, cebada y centeno, indicada para personas con celiaquía o sensibilidad al gluten.', 'AESAN', 'dieta', 'https://ejemplo.com/dieta-sin-gluten.jpg', TRUE),
('Dieta sin lactosa', 'Plan alimentario que excluye productos lácteos con lactosa, útil para personas con intolerancia a este azúcar.', 'EFSA', 'dieta', 'https://ejemplo.com/dieta-sin-lactosa.jpg', TRUE),
('Dieta hipocalórica', 'Dieta con un aporte energético reducido respecto a las necesidades del individuo, utilizada frecuentemente en procesos de pérdida de peso.', 'OMS', 'dieta', 'https://ejemplo.com/dieta-hipocalorica.jpg', TRUE),
('Dieta hiperproteica', 'Dieta rica en proteínas que busca preservar la masa muscular, especialmente en contextos de entrenamiento o pérdida de grasa.', 'NIH', 'dieta', 'https://ejemplo.com/dieta-hiperproteica.jpg', TRUE),
('Ayuno intermitente', 'Patrón de alimentación que alterna períodos de ingesta con períodos de ayuno, con el objetivo de mejorar la composición corporal o la salud metabólica.', 'Harvard Health Publishing', 'dieta', 'https://ejemplo.com/ayuno-intermitente.jpg', TRUE),
('Ejercicio aeróbico', 'Actividad física de intensidad moderada y larga duración que mejora la capacidad cardiovascular y la quema de grasa.', 'OMS', 'deporte', 'https://ejemplo.com/ejercicio-aerobico.jpg', TRUE),
('Ejercicio anaeróbico', 'Actividad de alta intensidad y corta duración que depende de reservas de energía sin oxígeno, como el entrenamiento de fuerza.', 'NIH', 'deporte', 'https://ejemplo.com/ejercicio-anaerobico.jpg', TRUE),
('VO2 máximo', 'Volumen máximo de oxígeno que el cuerpo puede utilizar durante el ejercicio intenso, indicador clave de resistencia cardiovascular.', 'EFSA', 'deporte', 'https://ejemplo.com/vo2max.jpg', TRUE),
('Recuperación muscular', 'Proceso fisiológico de regeneración de fibras musculares después del ejercicio, esencial para el rendimiento y prevención de lesiones.', 'FAO', 'deporte', 'https://ejemplo.com/recuperacion-muscular.jpg', TRUE),
('Gasto energético', 'Cantidad de energía que el cuerpo utiliza en reposo, actividad física y digestión.', 'EFSA', 'deporte', 'https://ejemplo.com/gasto-energetico.jpg', TRUE),
('Entrenamiento de resistencia', 'Actividad que implica la repetición de movimientos con carga para aumentar fuerza muscular y masa magra.', 'NIH', 'deporte', 'https://ejemplo.com/entrenamiento-resistencia.jpg', TRUE),
('Rendimiento deportivo', 'Capacidad de un atleta para ejecutar una actividad física con eficacia y eficiencia.', 'OMS', 'deporte', 'https://ejemplo.com/rendimiento-deportivo.jpg', TRUE);
INSERT INTO glosario (termino, definicion, fuente, categoria, imagen_url, visible)
VALUES
('Suplementación deportiva', 'Uso de productos nutricionales para optimizar el rendimiento, recuperación o salud en el contexto del deporte.', 'EFSA', 'deporte', 'https://ejemplo.com/suplementacion-deportiva.jpg', TRUE),
('Carga glucogénica', 'Técnica nutricional que busca maximizar los depósitos de glucógeno muscular antes de una competición.', 'NIH', 'deporte', 'https://ejemplo.com/carga-glucogenica.jpg', TRUE),
('Deshidratación', 'Estado de déficit de agua corporal que puede afectar el rendimiento físico y mental.', 'OMS', 'deporte', 'https://ejemplo.com/deshidratacion.jpg', TRUE),
('Ácido fólico', 'Forma sintética del folato, una vitamina B necesaria para la producción de ADN y el desarrollo celular, especialmente importante en el embarazo.', 'OMS', 'micronutriente', 'https://ejemplo.com/acido-folico.jpg', TRUE),
('Colina', 'Micronutriente relacionado con la vitamina B que participa en funciones hepáticas, desarrollo cerebral y síntesis de neurotransmisores.', 'NIH', 'micronutriente', 'https://ejemplo.com/colina.jpg', TRUE),
('Carotenoides', 'Pigmentos vegetales con propiedades antioxidantes, precursores de la vitamina A, presentes en frutas y verduras de color naranja y rojo.', 'EFSA', 'micronutriente', 'https://ejemplo.com/carotenoides.jpg', TRUE),
('Flavonoides', 'Compuestos bioactivos con función antioxidante y antiinflamatoria, presentes en frutas, verduras, té y vino tinto.', 'FAO', 'micronutriente', 'https://ejemplo.com/flavonoides.jpg', TRUE),
('Luteína', 'Carotenoide que se acumula en la retina y puede ayudar a proteger la salud ocular.', 'NIH', 'micronutriente', 'https://ejemplo.com/luteina.jpg', TRUE),
('Licopeno', 'Carotenoide con potentes propiedades antioxidantes, abundante en el tomate y otros frutos rojos.', 'EFSA', 'micronutriente', 'https://ejemplo.com/licopeno.jpg', TRUE),
('Inositol', 'Micronutriente involucrado en funciones celulares, hormonales y del sistema nervioso, a menudo clasificado con el complejo B.', 'FAO', 'micronutriente', 'https://ejemplo.com/inositol.jpg', TRUE),
('Coenzima Q10', 'Compuesto antioxidante que participa en la producción de energía celular y puede apoyar la salud cardiovascular.', 'NIH', 'micronutriente', 'https://ejemplo.com/coenzima-q10.jpg', TRUE),
('Taurina', 'Aminoácido sulfonado con funciones antioxidantes y reguladoras de la presión osmótica, presente en muchos tejidos humanos.', 'EFSA', 'micronutriente', 'https://ejemplo.com/taurina.jpg', TRUE),
('Betacaroteno', 'Precursor de la vitamina A con función antioxidante, presente en alimentos de origen vegetal como la zanahoria.', 'OMS', 'micronutriente', 'https://ejemplo.com/betacaroteno.jpg', TRUE),
('Alimento ultraprocesado', 'Producto industrial comestible con múltiples ingredientes y aditivos, asociado a un bajo valor nutricional y alto riesgo de enfermedades crónicas.', 'NOVA', 'otro', 'https://ejemplo.com/ultraprocesado.jpg', TRUE),
('Nutrición emocional', 'Relación entre la alimentación y las emociones, que puede afectar hábitos como el hambre emocional o el atracón.', 'Harvard Health', 'otro', 'https://ejemplo.com/nutricion-emocional.jpg', TRUE),
('Carga glucémica', 'Indicador que combina el índice glucémico y la cantidad de carbohidratos de un alimento para estimar su impacto glucémico real.', 'EFSA', 'otro', 'https://ejemplo.com/carga-glucemica.jpg', TRUE),
('Etiquetado nutricional', 'Información obligatoria o voluntaria que figura en los envases de alimentos sobre su composición y propiedades.', 'AESAN', 'otro', 'https://ejemplo.com/etiquetado.jpg', TRUE),
('Conservantes', 'Sustancias añadidas a los alimentos para evitar su deterioro microbiano o químico.', 'FAO', 'otro', 'https://ejemplo.com/conservantes.jpg', TRUE),
('Aditivos alimentarios', 'Sustancias utilizadas para mejorar el sabor, color, textura o conservación de los productos alimenticios.', 'EFSA', 'otro', 'https://ejemplo.com/aditivos.jpg', TRUE),
('Nutracéutico', 'Producto derivado de alimentos con beneficios médicos o de salud, incluyendo suplementos o alimentos funcionales.', 'NIH', 'otro', 'https://ejemplo.com/nutraceutico.jpg', TRUE),
('Transgénico', 'Organismo modificado genéticamente (OMG) al que se le han insertado genes de otra especie para mejorar su rendimiento o resistencia.', 'FAO', 'otro', 'https://ejemplo.com/transgenico.jpg', TRUE),
('Sostenibilidad alimentaria', 'Capacidad de los sistemas de alimentación para proporcionar alimentos seguros y nutritivos sin comprometer los recursos de las generaciones futuras.', 'FAO', 'otro', 'https://ejemplo.com/sostenibilidad.jpg', TRUE),
('Huella ecológica', 'Indicador del impacto ambiental de una persona o sistema, incluyendo la cantidad de recursos naturales consumidos.', 'WWF', 'otro', 'https://ejemplo.com/huella-ecologica.jpg', TRUE),
('Huella hídrica', 'Cantidad de agua utilizada directa o indirectamente para producir un alimento o servicio.', 'Water Footprint Network', 'otro', 'https://ejemplo.com/huella-hidrica.jpg', TRUE),
('Desperdicio alimentario', 'Pérdida de alimentos comestibles en cualquier etapa de la cadena alimentaria, desde la producción hasta el consumo.', 'FAO', 'otro', 'https://ejemplo.com/desperdicio-alimentario.jpg', TRUE),
('Proximidad alimentaria', 'Consumo de alimentos producidos localmente para reducir transporte, emisiones y apoyar la economía local.', 'Slow Food', 'otro', 'https://ejemplo.com/proximidad-alimentaria.jpg', TRUE),
('Alimentación consciente', 'Actitud de comer con plena atención al acto de alimentarse, respetando el hambre, la saciedad y el entorno.', 'Harvard T.H. Chan', 'otro', 'https://ejemplo.com/alimentacion-consciente.jpg', TRUE),
('Alimentación sostenible', 'Dieta saludable que tiene bajo impacto ambiental, protege la biodiversidad y promueve la equidad económica y social.', 'EFSA', 'otro', 'https://ejemplo.com/alimentacion-sostenible.jpg', TRUE),
('Ecoetiquetado', 'Sistema de etiquetado que informa sobre el impacto ambiental de un producto, promoviendo elecciones responsables.', 'UE', 'otro', 'https://ejemplo.com/ecoetiquetado.jpg', TRUE),
('Kilómetro cero', 'Concepto que promueve el consumo de alimentos producidos cerca del punto de venta o consumo, para reducir emisiones.', 'Slow Food', 'otro', 'https://ejemplo.com/km0.jpg', TRUE),
('Economía circular alimentaria', 'Modelo que busca reutilizar, reciclar y reducir el desperdicio en toda la cadena alimentaria.', 'Circular Economy EU', 'otro', 'https://ejemplo.com/economia-circular.jpg', TRUE);

INSERT INTO multimedia (titulo, descripcion, url, tipo, categoria, visible, fecha_publicacion)
VALUES
('¿Qué es una dieta saludable?', 'Vídeo educativo de la OMS que explica qué significa comer sano, con recomendaciones prácticas.', 
 'https://www.youtube.com/watch?v=3FFp9U2yNhc', 'video', 'nutricion', TRUE, '2021-05-12'),
('Nutrición y salud cardiovascular – Harvard T.H. Chan', 'Artículo web de la Escuela de Salud Pública de Harvard sobre cómo la dieta impacta en el corazón.', 
 'https://www.hsph.harvard.edu/nutritionsource/healthy-eating-plate/', 'web', 'salud', TRUE, '2023-07-20'),
('Ejercicio físico: guía visual para principiantes – NHS UK', 'Infografía sencilla sobre rutinas de ejercicio físico para todos los niveles, según el Servicio de Salud Británico.', 
 'https://www.nhs.uk/live-well/exercise/', 'web', 'ejercicio', TRUE, '2022-09-10'),
('Cómo leer una etiqueta nutricional – FDA (EE.UU.)', 'PDF oficial que enseña a interpretar etiquetas de alimentos en EE.UU., útil como ejemplo visual.', 
 'https://www.fda.gov/media/99069/download', 'pdf', 'nutricion', TRUE, '2021-04-01'),
('Mindful Eating explicado por The Nutrition Source – Harvard', 'Artículo que introduce la alimentación consciente con base científica y consejos prácticos.', 
 'https://www.hsph.harvard.edu/nutritionsource/mindful-eating/', 'web', 'mentalidad', TRUE, '2022-11-15'),
('Ejercicio físico: beneficios para la salud – Canal UNED', 'Vídeo educativo de la Universidad Nacional de Educación a Distancia sobre cómo el ejercicio impacta la salud física y mental.', 
 'https://www.youtube.com/watch?v=wFRkLfhXSaY', 'video', 'ejercicio', TRUE, '2020-04-28'),
('Rutina de ejercicios para hacer en casa sin material – Vitónica', 'Artículo con rutinas fáciles y sin equipamiento, ideal para principiantes.', 
 'https://www.vitonica.com/entrenamiento/rutina-ejercicios-casa-sin-material-para-principiantes', 'web', 'ejercicio', TRUE, '2023-01-10'),
('¿Cuánto ejercicio necesitas? – OMS', 'Infografía y guía de la Organización Mundial de la Salud con recomendaciones por edad y nivel.', 
 'https://www.who.int/es/news-room/fact-sheets/detail/physical-activity', 'web', 'ejercicio', TRUE, '2022-11-03'),
('Guía de entrenamiento de fuerza – EFSA/EuropeActive', 'PDF con pautas científicas para entrenar fuerza muscular de forma segura.', 
 'https://www.europeactive.eu/sites/europeactive.eu/files/projects/Guidelines_StructuredStrength.pdf', 'pdf', 'ejercicio', TRUE, '2021-09-01'),
('HIIT para principiantes en casa – Sergio Peinado', 'Vídeo dinámico en español con ejercicios HIIT guiados para mejorar resistencia y quemar grasa.', 
 'https://www.youtube.com/watch?v=z5qX2Nb4pmI', 'video', 'ejercicio', TRUE, '2023-02-15'),
 ('Alimentación antes y después del ejercicio – Clínica Mayo', 'Consejos prácticos sobre qué comer antes y después del entrenamiento para mejorar el rendimiento.', 
 'https://www.mayoclinic.org/es/healthy-lifestyle/fitness/in-depth/exercise/art-20045506', 'web', 'nutricion', TRUE, '2022-06-12'),
('¿Qué comer antes de entrenar? – Sergio Peinado', 'Vídeo en español con ejemplos reales de comidas pre-entreno según tipo de entrenamiento.', 
 'https://www.youtube.com/watch?v=Rj7QQoOnrRc', 'video', 'nutricion', TRUE, '2021-03-28'),
('Nutrición deportiva básica – MedlinePlus', 'Artículo introductorio que explica los fundamentos de la alimentación para deportistas.', 
 'https://medlineplus.gov/spanish/sportsnutrition.html', 'web', 'nutricion', TRUE, '2023-05-10'),
('Guía sobre proteínas para deportistas – Harvard Health', 'Análisis sobre cuánta proteína se necesita según el tipo de ejercicio y objetivos.', 
 'https://www.health.harvard.edu/blog/how-much-protein-do-you-need-every-day-201506183418', 'web', 'nutricion', TRUE, '2022-08-04'),
('Errores comunes al combinar ejercicio y dieta – PowerExplosive', 'Vídeo en español explicando mitos y errores comunes al entrenar y seguir una dieta.', 
 'https://www.youtube.com/watch?v=FeDQ6Y_OrJQ', 'video', 'nutricion', TRUE, '2022-10-20'),
 ('¿Qué es la creatina y cómo tomarla? – PowerExplosive', 'Vídeo detallado sobre la creatina, su eficacia, seguridad y cómo usarla para mejorar el rendimiento deportivo.', 
 'https://www.youtube.com/watch?v=Ulwbvf7UVdo', 'video', 'nutricion', TRUE, '2021-07-12'),
('Guía de suplementos deportivos – MedlinePlus', 'Artículo informativo sobre los principales suplementos utilizados en el deporte: proteína, creatina, cafeína y más.', 
 'https://medlineplus.gov/spanish/dietarysupplements.html', 'web', 'nutricion', TRUE, '2023-01-10'),
('¿Necesitas proteína en polvo? – Sergio Peinado', 'Vídeo explicativo para entender cuándo y cómo usar proteína en polvo en una dieta equilibrada.', 
 'https://www.youtube.com/watch?v=c2TPQJ_rMX8', 'video', 'nutricion', TRUE, '2022-05-20'),
('Suplementación en deportistas – European Food Safety Authority (EFSA)', 'Documento técnico que revisa la evidencia científica sobre suplementos populares en Europa.', 
 'https://www.efsa.europa.eu/en/topics/topic/nutrition', 'web', 'nutricion', TRUE, '2021-11-05'),
('Cafeína y rendimiento deportivo – G-SE', 'Artículo técnico que analiza los efectos de la cafeína sobre el rendimiento, la concentración y la fatiga.', 
 'https://g-se.com/la-cafeina-y-su-relacion-con-el-rendimiento-deportivo-bp-c57cfb26e6e29e', 'web', 'nutricion', TRUE, '2020-09-18'),
 ('Cómo llevar una dieta vegana equilibrada – Dietista-Nutricionista Lucía Redondo', 'Vídeo educativo que explica cómo estructurar una dieta 100% vegetal sin carencias.', 
 'https://www.youtube.com/watch?v=bAYOXIGMiDM', 'video', 'nutricion', TRUE, '2022-06-01'),
('¿Es posible ganar masa muscular siendo vegano? – Fitónica', 'Vídeo en español sobre estrategias para aumentar músculo con alimentación vegetal.', 
 'https://www.youtube.com/watch?v=iXQ1ix_XdWU', 'video', 'nutricion', TRUE, '2021-04-10'),
('Proteína vegetal vs animal – Veganismo en serio', 'Artículo detallado sobre la calidad y combinación de proteínas vegetales en dietas activas.', 
 'https://veganismo.org/2021/11/proteinas-vegetales-vs-animales/', 'web', 'nutricion', TRUE, '2021-11-05'),
('Vitamina B12 en dietas veganas – Vegan Society', 'Página oficial que explica la importancia de la suplementación con B12 y cómo tomarla correctamente.', 
 'https://www.vegansociety.com/resources/nutrition-and-health/vitamin-b12', 'web', 'nutricion', TRUE, '2023-03-20'),
('Suplementos clave en el deporte vegano – G-SE', 'Artículo técnico que analiza las necesidades especiales en deportistas veganos: B12, hierro, omega 3, creatina.', 
 'https://g-se.com/suplementos-clave-en-dietas-veganas-para-deportistas-bp-c603c0b3b53b4e', 'web', 'nutricion', TRUE, '2020-12-07'),
 ('Mindful Eating: cómo reconectar con la comida – TEDx Talks', 'Charla TEDx que explora cómo practicar la alimentación consciente para mejorar la relación con la comida.', 
 'https://www.youtube.com/watch?v=8QvWqw2sMHg', 'video', 'mentalidad', TRUE, '2019-11-13'),
('Cómo evitar comer por ansiedad – Psicóloga Miriam Al Adib', 'Vídeo que explica cómo gestionar el hambre emocional y las señales del cuerpo.', 
 'https://www.youtube.com/watch?v=x3OTOV5vP4M', 'video', 'mentalidad', TRUE, '2021-06-22'),
('Hábitos saludables y motivación – El Podcast de Cristina Mitre', 'Episodio donde se abordan los bloqueos mentales más comunes a la hora de cambiar de hábitos.', 
 'https://cristinamitre.substack.com/p/ep-200-motivacion-y-habitos', 'web', 'mentalidad', TRUE, '2022-09-25'),
('Autocompasión y alimentación – Psiquiatra Marian Rojas Estapé', 'Vídeo donde se explora la importancia de tratarse con amabilidad para mantener hábitos duraderos.', 
 'https://www.youtube.com/watch?v=8YScWkXhL8c', 'video', 'mentalidad', TRUE, '2022-02-10'),
('Cómo formar hábitos sostenibles – Fundación MAPFRE', 'Artículo con herramientas psicológicas para adoptar hábitos saludables sin frustración.', 
 'https://www.fundacionmapfre.org/salud/habitos-saludables/como-formar-habitos-saludables/', 'web', 'mentalidad', TRUE, '2023-04-03'),
 ('Ejercicio físico y salud mental – Colegio Oficial de Psicología de Madrid', 'Vídeo educativo sobre los beneficios del ejercicio para la ansiedad, la depresión y el bienestar general.', 
 'https://www.youtube.com/watch?v=Hb7cp3vW4aI', 'video', 'mentalidad', TRUE, '2022-03-15'),
('El deporte como medicina para la mente – Fundación Española del Corazón', 'Artículo que analiza cómo el deporte reduce el estrés, mejora el sueño y la autoestima.', 
 'https://fundaciondelcorazon.com/prevencion/ejercicio-fisico/2042-el-deporte-como-medicina-para-la-mente.html', 'web', 'mentalidad', TRUE, '2023-01-17'),
('Deporte y salud mental: el impacto psicológico del ejercicio – EFAD', 'Artículo técnico de la Escuela de Formación Abierta Deportiva sobre cómo influye el ejercicio en el cerebro.', 
 'https://efadeporte.com/deporte-y-salud-mental/', 'web', 'mentalidad', TRUE, '2021-10-05'),
('La importancia del ejercicio en trastornos mentales – Psicóloga Silvia Congost', 'Charla divulgativa sobre cómo el movimiento regula el estado de ánimo y combate la rumiación mental.', 
 'https://www.youtube.com/watch?v=b8_hvNFOTAc', 'video', 'mentalidad', TRUE, '2022-09-12'),
('Running y salud mental: ¿por qué correr mejora el ánimo? – Runners World España', 'Artículo que explica los mecanismos neurológicos y emocionales tras el “subidón del corredor”.', 
 'https://www.runnersworld.com/es/salud/a37185732/running-y-salud-mental/', 'web', 'mentalidad', TRUE, '2023-05-09');
 
INSERT INTO articulo (titulo, resumen, contenido, imagen_url, categoria, autor, fecha_publicacion, visible, visitas)
VALUES
(
  'Los pilares de una dieta equilibrada',
  'Descubre los principios básicos para mantener una alimentación saludable y sostenible en el tiempo.',
  'Una dieta equilibrada no se trata de contar calorías, sino de aportar al cuerpo todos los nutrientes esenciales: proteínas, grasas saludables, carbohidratos complejos, fibra, vitaminas y minerales. Incorporar variedad de alimentos, respetar las señales de hambre y saciedad, y adaptar las porciones a nuestras necesidades individuales son claves. También es importante evitar el exceso de ultraprocesados, priorizar alimentos frescos, hidratarse adecuadamente y mantener horarios estables de comida.',
  'https://ejemplo.com/imagenes/dieta-equilibrada.jpg',
  'nutricion',
  'Laura Martínez, Dietista-Nutricionista',
  '2024-04-12',
  TRUE,
  0
),
(
  '¿Qué son los ultraprocesados y cómo reducir su consumo?',
  'Aprende a identificar los alimentos ultraprocesados y por qué es recomendable limitarlos en tu dieta diaria.',
  'Los ultraprocesados son productos industriales con múltiples ingredientes, alto contenido en azúcares, grasas saturadas, aditivos y poca calidad nutricional. Algunos ejemplos comunes son bollería industrial, refrescos, snacks salados, embutidos o cereales azucarados. El consumo frecuente de estos alimentos se asocia con mayor riesgo de obesidad, enfermedades metabólicas y cardiovasculares. Para reducir su consumo, es útil planificar las comidas, cocinar más en casa y leer bien las etiquetas.',
  'https://ejemplo.com/imagenes/ultraprocesados.jpg',
  'nutricion',
  'Carlos Gómez, Nutricionista deportivo',
  '2024-05-05',
  TRUE,
  0
),
(
  'El papel de la fibra en la salud digestiva',
  'Conoce cómo la fibra alimentaria mejora tu tránsito intestinal, regula el azúcar en sangre y favorece la saciedad.',
  'La fibra es un componente vegetal no digerible que cumple múltiples funciones beneficiosas. La fibra soluble, presente en frutas, legumbres y avena, ayuda a controlar el colesterol y la glucosa. La fibra insoluble, abundante en verduras, cereales integrales y frutos secos, mejora el tránsito intestinal. Su consumo diario favorece la salud digestiva, reduce el riesgo de estreñimiento y promueve una microbiota intestinal equilibrada. Se recomienda consumir entre 25 y 30 g de fibra al día.',
  'https://ejemplo.com/imagenes/fibra-salud.jpg',
  'nutricion',
  'María López, Educadora en salud',
  '2024-06-01',
  TRUE,
  0
),
(
  'Cómo mejorar la calidad del sueño de forma natural',
  'Dormir bien es esencial para la salud física y mental. Te explicamos hábitos que favorecen un descanso reparador.',
  'La calidad del sueño impacta directamente en el sistema inmunológico, la concentración, el estado de ánimo y el metabolismo. Para mejorarla, es recomendable mantener horarios regulares, evitar el uso de pantallas antes de dormir, reducir el consumo de cafeína por la tarde, y crear un ambiente oscuro y silencioso. Técnicas como la meditación, respiración profunda o infusiones relajantes también pueden ayudar. Dormir entre 7 y 9 horas diarias es clave para el bienestar general.',
  'https://ejemplo.com/imagenes/sueno-saludable.jpg',
  'salud',
  'Sara Aguilar, Psicóloga especialista en salud',
  '2024-03-18',
  TRUE,
  0
),
(
  'Cómo fortalecer el sistema inmunológico con hábitos diarios',
  'Descubre qué factores fortalecen tus defensas y cómo mejorar tu salud inmunitaria con acciones cotidianas.',
  'El sistema inmunológico es la defensa natural del cuerpo frente a enfermedades. Para mantenerlo fuerte, es esencial llevar una alimentación rica en frutas, verduras, legumbres y frutos secos, realizar ejercicio físico moderado, dormir bien y reducir el estrés crónico. El contacto social, la exposición moderada al sol (vitamina D) y una buena hidratación también juegan un papel clave. Evitar el tabaco y el alcohol, y realizar chequeos médicos periódicos, cierra el círculo del autocuidado inmunológico.',
  'https://ejemplo.com/imagenes/sistema-inmune.jpg',
  'salud',
  'Dr. Javier Ruiz, Médico general',
  '2024-04-08',
  TRUE,
  0
),
(
  'El impacto del estrés crónico en la salud física',
  'El estrés sostenido no solo afecta la mente, también tiene consecuencias reales sobre el cuerpo.',
  'Cuando el estrés se vuelve crónico, el cuerpo permanece en estado de alerta constante, lo que puede derivar en insomnio, fatiga, hipertensión, problemas digestivos, debilitamiento del sistema inmune e incluso enfermedades cardiovasculares. Es importante aprender a identificar los síntomas del estrés sostenido y aplicar estrategias para gestionarlo: ejercicio regular, técnicas de relajación, establecer límites laborales, y buscar apoyo emocional. Cuidar la salud mental es una inversión en salud global.',
  'https://ejemplo.com/imagenes/estres-cuerpo.jpg',
  'salud',
  'Nuria Esteve, Terapeuta ocupacional',
  '2024-05-12',
  TRUE,
  0
),
(
  '3 desayunos saludables para empezar el día con energía',
  'Ideas de desayunos equilibrados, fáciles y rápidos, ideales para mantener buenos niveles de energía desde la mañana.',
  'El desayuno es una oportunidad para aportar nutrientes esenciales al cuerpo tras el ayuno nocturno. Aquí te proponemos tres opciones prácticas:\n\n1. **Tostadas de pan integral con aguacate, huevo duro y semillas de chía.** Aporta grasas saludables, proteína y fibra.\n\n2. **Yogur griego natural con frambuesas, copos de avena y nueces.** Ideal para cuidar la microbiota y obtener energía sostenida.\n\n3. **Batido vegetal con plátano, espinacas, bebida de almendras y proteína en polvo.** Muy saciante y completo para quien entrena por la mañana.',
  'https://ejemplo.com/imagenes/desayunos-saludables.jpg',
  'recetas',
  'Clara Soler, Técnica en Dietética',
  '2024-03-02',
  TRUE,
  0
),
(
  'Ideas de cenas ligeras y nutritivas para dormir mejor',
  'Comer bien por la noche puede ayudarte a descansar mejor. Estas recetas son saciantes pero suaves para la digestión.',
  'Las cenas copiosas dificultan el descanso. Aquí van tres ideas ligeras:\n\n1. **Crema de calabacín con picatostes integrales y huevo poché.** Rica en fibra y proteína, ideal para reconfortar el estómago.\n\n2. **Salteado de tofu con verduras y salsa de soja baja en sal.** Aporte vegetal con buena cantidad de proteína.\n\n3. **Tortilla francesa con espinacas y ensalada de tomate cherry.** Fácil, rápida y equilibrada.\n\nLo ideal es cenar al menos 2 horas antes de irse a la cama para favorecer la digestión.',
  'https://ejemplo.com/imagenes/cenas-nutritivas.jpg',
  'recetas',
  'Lucía Castaño, Coach en nutrición consciente',
  '2024-04-20',
  TRUE,
  0
),
(
  'Snacks saludables para media mañana o tarde',
  'Evita los ultraprocesados y opta por estos snacks caseros ricos en fibra, vitaminas y energía.',
  'Comer entre horas no tiene por qué ser insano. Aquí tienes opciones de snacks saludables:\n\n- **Hummus con palitos de zanahoria y pepino.** Fuente vegetal de proteína y fibra.\n- **Bol de fruta fresca con semillas de lino.** Ideal para aportar energía y micronutrientes.\n- **Tostadas de maíz con crema de cacahuete 100% natural.** Perfecto para media mañana o merienda tras entrenar.\n- **Puñado de frutos secos naturales (nueces, almendras, anacardos).** Rico en grasas saludables y saciante.\n\nElegir snacks reales te ayuda a mantener un patrón saludable sin restricciones.',
  'https://ejemplo.com/imagenes/snacks-saludables.jpg',
  'recetas',
  'Andrés Romero, Educador nutricional',
  '2024-05-30',
  TRUE,
  0
),
(
  '¿Cuánto ejercicio necesitas a la semana para estar saludable?',
  'Descubre las recomendaciones oficiales de actividad física y cómo adaptarlas a tu estilo de vida.',
  'La Organización Mundial de la Salud recomienda un mínimo de 150 minutos semanales de actividad aeróbica moderada o 75 minutos intensa, combinados con ejercicios de fuerza al menos 2 días a la semana. Esto incluye caminar rápido, nadar, bailar, correr, hacer pesas o yoga. Si llevas una vida sedentaria, puedes empezar con 10-15 minutos diarios e ir aumentando progresivamente. Lo importante no es hacer mucho de golpe, sino crear un hábito sostenible.',
  'https://ejemplo.com/imagenes/actividad-fisica.jpg',
  'deporte',
  'Sonia Navarro, Licenciada en Ciencias del Deporte',
  '2024-04-01',
  TRUE,
  0
),
(
  'Entrenamiento de fuerza: beneficios más allá de los músculos',
  'Hacer pesas o ejercicios con el propio peso no es solo para quienes quieren ganar volumen. Tiene múltiples beneficios.',
  'El entrenamiento de fuerza mejora la masa muscular, la densidad ósea, el metabolismo y la salud cardiovascular. Además, es clave para prevenir lesiones, mantener una buena postura y retrasar el envejecimiento físico. No hace falta ir al gimnasio: ejercicios como sentadillas, flexiones, planchas o subir escaleras también cuentan. Incluir al menos 2 sesiones semanales puede marcar una gran diferencia en tu salud a largo plazo.',
  'https://ejemplo.com/imagenes/fuerza-beneficios.jpg',
  'deporte',
  'Iván Torres, Preparador físico',
  '2024-04-18',
  TRUE,
  0
),
(
  'Cómo empezar a correr sin lesionarte: guía para principiantes',
  'Si estás pensando en empezar a correr, esta guía te ayudará a hacerlo de forma segura y efectiva.',
  'Correr es una forma excelente de mejorar la salud cardiovascular, liberar estrés y aumentar la resistencia. Pero empezar demasiado rápido o sin técnica puede provocar lesiones. Para iniciarte correctamente, comienza con caminatas rápidas alternadas con pequeños tramos de trote. Usa calzado adecuado, evita superficies muy duras, y escucha a tu cuerpo. Lo ideal es seguir un plan progresivo como el "Couch to 5K" y mantener la constancia más allá de la motivación inicial.',
  'https://ejemplo.com/imagenes/empezar-a-correr.jpg',
  'deporte',
  'Nerea Vidal, Entrenadora personal',
  '2024-05-07',
  TRUE,
  0
),
(
  '¿Qué es la huella ecológica y cómo reducirla desde tu cocina?',
  'La forma en que comemos impacta en el medio ambiente. Aprende cómo minimizar tu huella ecológica desde casa.',
  'La huella ecológica mide el impacto ambiental de nuestras acciones. En la alimentación, esta huella se refleja en la cantidad de recursos utilizados para producir, transportar y desechar los alimentos. Reducir el consumo de carne, optar por productos locales y de temporada, evitar el desperdicio alimentario y elegir envases reutilizables son pasos clave. Cocinar con planificación, congelar sobras y apoyar mercados de proximidad también ayuda a construir un sistema alimentario más sostenible.',
  'https://ejemplo.com/imagenes/huella-ecologica-cocina.jpg',
  'otro',
  'Helena Puig, Ambientalista y divulgadora',
  '2024-03-10',
  TRUE,
  0
),
(
  'La importancia del descanso en el bienestar integral',
  'Descansar bien no solo es dormir. Te explicamos por qué el descanso físico, mental y emocional es clave para tu salud.',
  'El descanso integral va más allá del sueño. También incluye momentos de desconexión mental, pausas activas, tiempo libre sin pantallas y espacios de autocuidado. En un mundo acelerado, no descansar correctamente puede afectar la concentración, el estado de ánimo y la salud física. Incorporar microdescansos durante el día, priorizar actividades recreativas, y respetar los ritmos circadianos mejora significativamente la calidad de vida.',
  'https://ejemplo.com/imagenes/descanso-bienestar.jpg',
  'otro',
  'Martina Rey, Psicóloga holística',
  '2024-04-15',
  TRUE,
  0
),
(
  'Cómo construir hábitos duraderos: más allá de la motivación',
  'El cambio real no viene de la fuerza de voluntad, sino de construir sistemas sostenibles. Aprende a formar hábitos.',
  'Muchos inician cambios con entusiasmo pero abandonan al poco tiempo. La clave está en transformar pequeñas acciones en rutinas diarias. Empezar poco a poco, usar recordatorios visuales, crear contextos favorables y recompensar el progreso ayuda a consolidar nuevos hábitos. Además, es importante aceptar retrocesos como parte del proceso y centrarse en la constancia más que en la perfección. No necesitas motivación constante, necesitas estructura y compromiso amable contigo mismo.',
  'https://ejemplo.com/imagenes/habitos-duraderos.jpg',
  'otro',
  'Raúl Estrada, Coach de hábitos',
  '2024-05-26',
  TRUE,
  0
);

INSERT INTO comida_modelo (
    nombre, tipo_comida, calorias_totales,
    apta_diabetes, apta_hipertension, apta_hipercolesterolemia, apta_celiacos, apta_renal,
    apta_anemia, apta_obesidad, apta_hipotiroidismo, apta_colon_irritable,
    sin_lactosa, sin_frutos_secos, sin_marisco, sin_pescado_azul,
    sin_huevo, sin_soja, sin_legumbres, sin_sesamo
) VALUES
-- Desayuno 1: Avena con bebida de almendra, plátano y semillas de chía
('Avena con bebida de almendra, plátano y semillas de chía', 'desayuno', 350,
 TRUE, TRUE, TRUE, TRUE, TRUE,
 TRUE, TRUE, TRUE, TRUE,
 TRUE, FALSE, TRUE, TRUE,
 TRUE, TRUE, TRUE, FALSE),

-- Desayuno 2: Pan sin gluten con hummus y tomate cherry
('Pan sin gluten con hummus y tomate cherry', 'desayuno', 300,
 TRUE, TRUE, TRUE, TRUE, TRUE,
 TRUE, TRUE, TRUE, TRUE,
 TRUE, TRUE, TRUE, TRUE,
 TRUE, FALSE, FALSE, FALSE),

-- Desayuno 3: Yogur vegetal con frambuesas y semillas de lino
('Yogur vegetal con frambuesas y semillas de lino', 'desayuno', 250,
 TRUE, TRUE, TRUE, TRUE, TRUE,
 TRUE, TRUE, TRUE, TRUE,
 TRUE, TRUE, TRUE, TRUE,
 TRUE, FALSE, TRUE, FALSE);

INSERT INTO comida_ingrediente (comida_modelo_id, ingrediente_id, cantidad, unidad) VALUES
(1, 127, 40, 'g'),    -- avena en copos
(1, 171, 200, 'ml'),  -- bebida de almendra
(1, 37, 1, 'unidad'),-- plátano
(1, 227, 10, 'g'),    -- semillas de chía
(2, 154, 60, 'g'),    -- pan sin gluten
(2, 6, 40, 'g'),    -- hummus
(2, 7, 50, 'g'),    -- tomate cherry
(3, 8, 125, 'g'),   -- yogur vegetal
(3, 9, 50, 'g'),    -- frambuesas
(3, 10, 10, 'g');   -- semillas de lino
